// Code generated by "terraform-provider-keyhub-generator"; DO NOT EDIT.

//lint:ignore U1000 Ignore unused functions in generated code
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func fillDataStructFromTFObjectRSAuditInfo(data *auditInfoDataRS, obj types.Object) {
	data.CreatedAt = obj.Attributes()["created_at"].(basetypes.StringValue)
	data.CreatedBy = obj.Attributes()["created_by"].(basetypes.StringValue)
	data.LastModifiedAt = obj.Attributes()["last_modified_at"].(basetypes.StringValue)
	data.LastModifiedBy = obj.Attributes()["last_modified_by"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSGeneratedSecret(data *generatedSecretDataRS, obj types.Object) {
	data.GeneratedSecret = obj.Attributes()["generated_secret"].(basetypes.StringValue)
	data.OldSecret = obj.Attributes()["old_secret"].(basetypes.StringValue)
	data.Regenerate = obj.Attributes()["regenerate"].(basetypes.BoolValue)
}

func fillDataStructFromTFObjectRSLinkable(data *linkableDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSNonLinkable(data *nonLinkableDataRS, obj types.Object) {
}

func fillDataStructFromTFObjectRSRestLink(data *restLinkDataRS, obj types.Object) {
	data.Href = obj.Attributes()["href"].(basetypes.StringValue)
	data.ID = obj.Attributes()["id"].(basetypes.Int64Value)
	data.Rel = obj.Attributes()["rel"].(basetypes.StringValue)
	data.TypeEscaped = obj.Attributes()["type_escaped"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSAuthAccountPrimer(data *authAccountPrimerDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.DisplayName = obj.Attributes()["display_name"].(basetypes.StringValue)
	data.LastActive = obj.Attributes()["last_active"].(basetypes.StringValue)
	data.Username = obj.Attributes()["username"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.Validity = obj.Attributes()["validity"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSAuthPermission(data *authPermissionDataRS, obj types.Object) {
	data.Full = obj.Attributes()["full"].(basetypes.StringValue)
	data.Instances = obj.Attributes()["instances"].(basetypes.ListValue)
	data.Operations = obj.Attributes()["operations"].(basetypes.ListValue)
	data.TypeEscaped = obj.Attributes()["type_escaped"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSCertificateCertificatePrimer(data *certificateCertificatePrimerDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Alias = obj.Attributes()["alias"].(basetypes.StringValue)
	data.CertificateCertificatePrimerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.CertificateData = obj.Attributes()["certificate_data"].(basetypes.ListValue)
	data.Expiration = obj.Attributes()["expiration"].(basetypes.StringValue)
	data.FingerprintSha1 = obj.Attributes()["fingerprint_sha1"].(basetypes.StringValue)
	data.FingerprintSha256 = obj.Attributes()["fingerprint_sha256"].(basetypes.StringValue)
	data.Global = obj.Attributes()["global"].(basetypes.BoolValue)
	data.SubjectDN = obj.Attributes()["subject_dn"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSClientApplicationVaultVaultRecord(data *clientApplicationVaultVaultRecordDataRS, obj types.Object) {
	data.ClientApplicationUUID = obj.Attributes()["client_application_uuid"].(basetypes.StringValue)
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Color = obj.Attributes()["color"].(basetypes.StringValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.ShareEndTime = obj.Attributes()["share_end_time"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.DeleteTile = obj.Attributes()["delete_tile"].(basetypes.BoolValue)
	data.ParentUUID = obj.Attributes()["parent_uuid"].(basetypes.StringValue)
	data.PasswordMetadata = obj.Attributes()["password_metadata"].(basetypes.ObjectValue)
	data.Secret = obj.Attributes()["secret"].(basetypes.ObjectValue)
	data.ShareSummary = obj.Attributes()["share_summary"].(basetypes.ObjectValue)
	data.Shares = obj.Attributes()["shares"].(basetypes.ListValue)
	data.Tile = obj.Attributes()["tile"].(basetypes.ObjectValue)
	data.Vaultholder = obj.Attributes()["vaultholder"].(basetypes.ObjectValue)
	data.Derived = obj.Attributes()["derived"].(basetypes.BoolValue)
	data.EndDate = obj.Attributes()["end_date"].(basetypes.StringValue)
	data.Filename = obj.Attributes()["filename"].(basetypes.StringValue)
	data.Types = obj.Attributes()["types"].(basetypes.ListValue)
	data.URL = obj.Attributes()["url"].(basetypes.StringValue)
	data.Username = obj.Attributes()["username"].(basetypes.StringValue)
	data.WarningPeriod = obj.Attributes()["warning_period"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSClientClientApplication(data *clientClientApplicationDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.ClientClientApplicationPrimerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.ClientID = obj.Attributes()["client_id"].(basetypes.StringValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.Scopes = obj.Attributes()["scopes"].(basetypes.ListValue)
	data.SsoApplication = obj.Attributes()["sso_application"].(basetypes.BoolValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.DeleteTile = obj.Attributes()["delete_tile"].(basetypes.BoolValue)
	data.Groupclients = obj.Attributes()["groupclients"].(basetypes.ListValue)
	data.Groups = obj.Attributes()["groups"].(basetypes.ListValue)
	data.Secret = obj.Attributes()["secret"].(basetypes.ObjectValue)
	data.Tile = obj.Attributes()["tile"].(basetypes.ObjectValue)
	data.VaultRecordCount = obj.Attributes()["vault_record_count"].(basetypes.Int64Value)
	data.LastModifiedAt = obj.Attributes()["last_modified_at"].(basetypes.StringValue)
	data.OwnerUUID = obj.Attributes()["owner_uuid"].(basetypes.StringValue)
	data.TechnicalAdministratorUUID = obj.Attributes()["technical_administrator_uuid"].(basetypes.StringValue)
	data.LDAPClient = obj.Attributes()["ldap_client"].(basetypes.ObjectValue)
	data.OAuth2Client = obj.Attributes()["o_auth2_client"].(basetypes.ObjectValue)
	data.Saml2Client = obj.Attributes()["saml2_client"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSClientClientApplicationLinkableWrapper(data *clientClientApplicationLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSClientClientApplicationPrimer(data *clientClientApplicationPrimerDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.ClientClientApplicationPrimerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.ClientID = obj.Attributes()["client_id"].(basetypes.StringValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.Scopes = obj.Attributes()["scopes"].(basetypes.ListValue)
	data.SsoApplication = obj.Attributes()["sso_application"].(basetypes.BoolValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSClientClientApplication_additionalObjects(data *clientClientApplication_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.DeleteTile = obj.Attributes()["delete_tile"].(basetypes.BoolValue)
	data.Groupclients = obj.Attributes()["groupclients"].(basetypes.ListValue)
	data.Groups = obj.Attributes()["groups"].(basetypes.ListValue)
	data.Secret = obj.Attributes()["secret"].(basetypes.ObjectValue)
	data.Tile = obj.Attributes()["tile"].(basetypes.ObjectValue)
	data.VaultRecordCount = obj.Attributes()["vault_record_count"].(basetypes.Int64Value)
}

func fillDataStructFromTFObjectRSClientLdapClient(data *clientLdapClientDataRS, obj types.Object) {
	data.BindDN = obj.Attributes()["bind_dn"].(basetypes.StringValue)
	data.ClientCertificateUUID = obj.Attributes()["client_certificate_uuid"].(basetypes.StringValue)
	data.ShareSecretInVault = obj.Attributes()["share_secret_in_vault"].(basetypes.BoolValue)
	data.SharedSecretUUID = obj.Attributes()["shared_secret_uuid"].(basetypes.StringValue)
	data.UsedForProvisioning = obj.Attributes()["used_for_provisioning"].(basetypes.BoolValue)
}

func fillDataStructFromTFObjectRSClientOAuth2Client(data *clientOAuth2ClientDataRS, obj types.Object) {
	data.AccountPermissions = obj.Attributes()["account_permissions"].(basetypes.ListValue)
	data.Attributes = obj.Attributes()["attributes"].(basetypes.MapValue)
	data.CallbackURI = obj.Attributes()["callback_uri"].(basetypes.StringValue)
	data.Confidential = obj.Attributes()["confidential"].(basetypes.BoolValue)
	data.DebugMode = obj.Attributes()["debug_mode"].(basetypes.BoolValue)
	data.IDTokenClaims = obj.Attributes()["id_token_claims"].(basetypes.StringValue)
	data.InitiateLoginURI = obj.Attributes()["initiate_login_uri"].(basetypes.StringValue)
	data.ResourceURIs = obj.Attributes()["resource_uris"].(basetypes.StringValue)
	data.ShareSecretInVault = obj.Attributes()["share_secret_in_vault"].(basetypes.BoolValue)
	data.SharedSecretUUID = obj.Attributes()["shared_secret_uuid"].(basetypes.StringValue)
	data.ShowLandingPage = obj.Attributes()["show_landing_page"].(basetypes.BoolValue)
	data.UseClientCredentials = obj.Attributes()["use_client_credentials"].(basetypes.BoolValue)
}

func fillDataStructFromTFObjectRSClientOAuth2ClientPermission(data *clientOAuth2ClientPermissionDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.ForGroupUUID = obj.Attributes()["for_group_uuid"].(basetypes.StringValue)
	data.ForSystemUUID = obj.Attributes()["for_system_uuid"].(basetypes.StringValue)
	data.Value = obj.Attributes()["value"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSClientOAuth2ClientPermissionWithClient(data *clientOAuth2ClientPermissionWithClientDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.ForGroupUUID = obj.Attributes()["for_group_uuid"].(basetypes.StringValue)
	data.ForSystemUUID = obj.Attributes()["for_system_uuid"].(basetypes.StringValue)
	data.Value = obj.Attributes()["value"].(basetypes.StringValue)
	data.ClientUUID = obj.Attributes()["client_uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSClientOAuth2ClientPermissionWithClientLinkableWrapper(data *clientOAuth2ClientPermissionWithClientLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSClientOAuth2ClientPermission_additionalObjects(data *clientOAuth2ClientPermission_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSClientSaml2Client(data *clientSaml2ClientDataRS, obj types.Object) {
	data.Attributes = obj.Attributes()["attributes"].(basetypes.MapValue)
	data.Metadata = obj.Attributes()["metadata"].(basetypes.StringValue)
	data.MetadataURL = obj.Attributes()["metadata_url"].(basetypes.StringValue)
	data.SubjectFormat = obj.Attributes()["subject_format"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSDirectoryAccountDirectory(data *directoryAccountDirectoryDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.AccountValiditySupported = obj.Attributes()["account_validity_supported"].(basetypes.BoolValue)
	data.Active = obj.Attributes()["active"].(basetypes.BoolValue)
	data.DirectoryAccountDirectoryPrimerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.Markers = obj.Attributes()["markers"].(basetypes.ObjectValue)
	data.Status = obj.Attributes()["status"].(basetypes.ObjectValue)
	data.BaseOrganizationalUnitUUID = obj.Attributes()["base_organizational_unit_uuid"].(basetypes.StringValue)
	data.DefaultDirectory = obj.Attributes()["default_directory"].(basetypes.BoolValue)
	data.HelpdeskGroupUUID = obj.Attributes()["helpdesk_group_uuid"].(basetypes.StringValue)
	data.Restrict2fa = obj.Attributes()["restrict2fa"].(basetypes.BoolValue)
	data.RotatingPassword = obj.Attributes()["rotating_password"].(basetypes.StringValue)
	data.UsernameCustomizable = obj.Attributes()["username_customizable"].(basetypes.BoolValue)
	data.InternalDirectory = obj.Attributes()["internal_directory"].(basetypes.ObjectValue)
	data.LDAPDirectory = obj.Attributes()["l_d_a_p_directory"].(basetypes.ObjectValue)
	data.MaintenanceDirectory = obj.Attributes()["maintenance_directory"].(basetypes.ObjectValue)
	data.OIDCDirectory = obj.Attributes()["o_id_c_directory"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSDirectoryAccountDirectoryLinkableWrapper(data *directoryAccountDirectoryLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSDirectoryAccountDirectoryPrimer(data *directoryAccountDirectoryPrimerDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.AccountValiditySupported = obj.Attributes()["account_validity_supported"].(basetypes.BoolValue)
	data.Active = obj.Attributes()["active"].(basetypes.BoolValue)
	data.DirectoryAccountDirectoryPrimerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSDirectoryAccountDirectoryStatusReport(data *directoryAccountDirectoryStatusReportDataRS, obj types.Object) {
	data.Accounts = obj.Attributes()["accounts"].(basetypes.Int64Value)
	data.Reason = obj.Attributes()["reason"].(basetypes.StringValue)
	data.Status = obj.Attributes()["status"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSDirectoryAccountDirectorySummary(data *directoryAccountDirectorySummaryDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.DirectoryAccountDirectorySummaryType = obj.Attributes()["type"].(basetypes.StringValue)
	data.DomainRestriction = obj.Attributes()["domain_restriction"].(basetypes.StringValue)
	data.FullyResolvedIssuer = obj.Attributes()["fully_resolved_issuer"].(basetypes.StringValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.Status = obj.Attributes()["status"].(basetypes.ObjectValue)
	data.UsernameCustomizable = obj.Attributes()["username_customizable"].(basetypes.BoolValue)
}

func fillDataStructFromTFObjectRSDirectoryAccountDirectorySummaryLinkableWrapper(data *directoryAccountDirectorySummaryLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSDirectoryAccountDirectory_additionalObjects(data *directoryAccountDirectory_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.Markers = obj.Attributes()["markers"].(basetypes.ObjectValue)
	data.Status = obj.Attributes()["status"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSDirectoryInternalDirectory(data *directoryInternalDirectoryDataRS, obj types.Object) {
	data.OwnerUUID = obj.Attributes()["owner_uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSDirectoryLDAPDirectory(data *directoryLDAPDirectoryDataRS, obj types.Object) {
	data.AttributesToStore = obj.Attributes()["attributes_to_store"].(basetypes.StringValue)
	data.BaseDN = obj.Attributes()["base_dn"].(basetypes.StringValue)
	data.ClientCertificateUUID = obj.Attributes()["client_certificate_uuid"].(basetypes.StringValue)
	data.Dialect = obj.Attributes()["dialect"].(basetypes.StringValue)
	data.FailoverHost = obj.Attributes()["failover_host"].(basetypes.StringValue)
	data.FailoverTrustedCertificateUUID = obj.Attributes()["failover_trusted_certificate_uuid"].(basetypes.StringValue)
	data.Host = obj.Attributes()["host"].(basetypes.StringValue)
	data.PasswordRecovery = obj.Attributes()["password_recovery"].(basetypes.StringValue)
	data.Port = obj.Attributes()["port"].(basetypes.Int64Value)
	data.SearchBindDN = obj.Attributes()["search_bind_dn"].(basetypes.StringValue)
	data.SearchBindPassword = obj.Attributes()["search_bind_password"].(basetypes.StringValue)
	data.SearchFilter = obj.Attributes()["search_filter"].(basetypes.StringValue)
	data.TLS = obj.Attributes()["tls"].(basetypes.StringValue)
	data.TrustedCertificateUUID = obj.Attributes()["trusted_certificate_uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSDirectoryMaintenanceDirectory(data *directoryMaintenanceDirectoryDataRS, obj types.Object) {
}

func fillDataStructFromTFObjectRSDirectoryOIDCDirectory(data *directoryOIDCDirectoryDataRS, obj types.Object) {
	data.AcrValues = obj.Attributes()["acr_values"].(basetypes.StringValue)
	data.AttributesToStore = obj.Attributes()["attributes_to_store"].(basetypes.StringValue)
	data.ClientID = obj.Attributes()["client_id"].(basetypes.StringValue)
	data.ClientSecret = obj.Attributes()["client_secret"].(basetypes.StringValue)
	data.DomainRestriction = obj.Attributes()["domain_restriction"].(basetypes.StringValue)
	data.Enforces2fa = obj.Attributes()["enforces2fa"].(basetypes.BoolValue)
	data.FullyResolvedIssuer = obj.Attributes()["fully_resolved_issuer"].(basetypes.StringValue)
	data.Issuer = obj.Attributes()["issuer"].(basetypes.StringValue)
	data.LogoutURL = obj.Attributes()["logout_url"].(basetypes.StringValue)
	data.SendLoginHint = obj.Attributes()["send_login_hint"].(basetypes.BoolValue)
	data.VendorEscaped = obj.Attributes()["vendor_escaped"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSGroupAuthorizedGroupsWrapper(data *groupAuthorizedGroupsWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
	data.GroupCount = obj.Attributes()["group_count"].(basetypes.Int64Value)
}

func fillDataStructFromTFObjectRSGroupGroup(data *groupGroupDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Admin = obj.Attributes()["admin"].(basetypes.BoolValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.OrganizationalUnitUUID = obj.Attributes()["organizational_unit_uuid"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.Accounts = obj.Attributes()["accounts"].(basetypes.ListValue)
	data.AdministeredClients = obj.Attributes()["administered_clients"].(basetypes.ListValue)
	data.AdministeredSystems = obj.Attributes()["administered_systems"].(basetypes.ListValue)
	data.Admins = obj.Attributes()["admins"].(basetypes.ListValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.AuthorizedGroups = obj.Attributes()["authorized_groups"].(basetypes.ObjectValue)
	data.ClientPermissions = obj.Attributes()["client_permissions"].(basetypes.ListValue)
	data.Clients = obj.Attributes()["clients"].(basetypes.ListValue)
	data.ContentAdministeredSystems = obj.Attributes()["content_administered_systems"].(basetypes.ListValue)
	data.Groupauditinginfo = obj.Attributes()["groupauditinginfo"].(basetypes.ObjectValue)
	data.Groupinfo = obj.Attributes()["groupinfo"].(basetypes.ObjectValue)
	data.Helpdesk = obj.Attributes()["helpdesk"].(basetypes.ListValue)
	data.Markers = obj.Attributes()["markers"].(basetypes.ObjectValue)
	data.Myaccount = obj.Attributes()["myaccount"].(basetypes.ObjectValue)
	data.Mydelegatedaccount = obj.Attributes()["mydelegatedaccount"].(basetypes.ObjectValue)
	data.NestedGroups = obj.Attributes()["nested_groups"].(basetypes.ListValue)
	data.OwnedClients = obj.Attributes()["owned_clients"].(basetypes.ListValue)
	data.OwnedDirectories = obj.Attributes()["owned_directories"].(basetypes.ListValue)
	data.OwnedGroupsOnSystem = obj.Attributes()["owned_groups_on_system"].(basetypes.ObjectValue)
	data.OwnedOrganizationalUnits = obj.Attributes()["owned_organizational_units"].(basetypes.ListValue)
	data.OwnedSystems = obj.Attributes()["owned_systems"].(basetypes.ListValue)
	data.RecentAudits = obj.Attributes()["recent_audits"].(basetypes.ListValue)
	data.Requeststatus = obj.Attributes()["requeststatus"].(basetypes.StringValue)
	data.ServiceAccounts = obj.Attributes()["service_accounts"].(basetypes.ListValue)
	data.Systems = obj.Attributes()["systems"].(basetypes.ListValue)
	data.Vault = obj.Attributes()["vault"].(basetypes.ObjectValue)
	data.Webhooks = obj.Attributes()["webhooks"].(basetypes.ListValue)
	data.ApplicationAdministration = obj.Attributes()["application_administration"].(basetypes.BoolValue)
	data.AuditConfig = obj.Attributes()["audit_config"].(basetypes.ObjectValue)
	data.AuditRequested = obj.Attributes()["audit_requested"].(basetypes.BoolValue)
	data.Auditor = obj.Attributes()["auditor"].(basetypes.BoolValue)
	data.AuthorizingGroupAuditingUUID = obj.Attributes()["authorizing_group_auditing_uuid"].(basetypes.StringValue)
	data.AuthorizingGroupDelegationUUID = obj.Attributes()["authorizing_group_delegation_uuid"].(basetypes.StringValue)
	data.AuthorizingGroupMembershipUUID = obj.Attributes()["authorizing_group_membership_uuid"].(basetypes.StringValue)
	data.AuthorizingGroupProvisioningUUID = obj.Attributes()["authorizing_group_provisioning_uuid"].(basetypes.StringValue)
	data.AuthorizingGroupTypes = obj.Attributes()["authorizing_group_types"].(basetypes.ListValue)
	data.ClassificationUUID = obj.Attributes()["classification_uuid"].(basetypes.StringValue)
	data.Description = obj.Attributes()["description"].(basetypes.StringValue)
	data.ExtendedAccess = obj.Attributes()["extended_access"].(basetypes.StringValue)
	data.HideAuditTrail = obj.Attributes()["hide_audit_trail"].(basetypes.BoolValue)
	data.NestedUnderUUID = obj.Attributes()["nested_under_uuid"].(basetypes.StringValue)
	data.PrivateGroup = obj.Attributes()["private_group"].(basetypes.BoolValue)
	data.RecordTrail = obj.Attributes()["record_trail"].(basetypes.BoolValue)
	data.RotatingPasswordRequired = obj.Attributes()["rotating_password_required"].(basetypes.BoolValue)
	data.SingleManaged = obj.Attributes()["single_managed"].(basetypes.BoolValue)
	data.VaultRecovery = obj.Attributes()["vault_recovery"].(basetypes.StringValue)
	data.VaultRequiresActivation = obj.Attributes()["vault_requires_activation"].(basetypes.BoolValue)
}

func fillDataStructFromTFObjectRSGroupGroupAccount(data *groupGroupAccountDataRS, obj types.Object) {
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.DirectoryUUID = obj.Attributes()["directory_uuid"].(basetypes.StringValue)
	data.DisconnectedNested = obj.Attributes()["disconnected_nested"].(basetypes.BoolValue)
	data.EndDate = obj.Attributes()["end_date"].(basetypes.StringValue)
	data.LastUsed = obj.Attributes()["last_used"].(basetypes.StringValue)
	data.Nested = obj.Attributes()["nested"].(basetypes.BoolValue)
	data.ProvisioningEndTime = obj.Attributes()["provisioning_end_time"].(basetypes.StringValue)
	data.Rights = obj.Attributes()["rights"].(basetypes.StringValue)
	data.TwoFactorStatus = obj.Attributes()["two_factor_status"].(basetypes.StringValue)
	data.VisibleForProvisioning = obj.Attributes()["visible_for_provisioning"].(basetypes.BoolValue)
}

func fillDataStructFromTFObjectRSGroupGroupAccountLinkableWrapper(data *groupGroupAccountLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSGroupGroupAccount_additionalObjects(data *groupGroupAccount_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSGroupGroupAudit(data *groupGroupAuditDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Accounts = obj.Attributes()["accounts"].(basetypes.ListValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.Comment = obj.Attributes()["comment"].(basetypes.StringValue)
	data.CreatedAt = obj.Attributes()["created_at"].(basetypes.StringValue)
	data.CreatedBy = obj.Attributes()["created_by"].(basetypes.StringValue)
	data.GroupName = obj.Attributes()["group_name"].(basetypes.StringValue)
	data.NameOnAudit = obj.Attributes()["name_on_audit"].(basetypes.StringValue)
	data.ReviewedAt = obj.Attributes()["reviewed_at"].(basetypes.StringValue)
	data.ReviewedBy = obj.Attributes()["reviewed_by"].(basetypes.StringValue)
	data.Status = obj.Attributes()["status"].(basetypes.StringValue)
	data.SubmittedAt = obj.Attributes()["submitted_at"].(basetypes.StringValue)
	data.SubmittedBy = obj.Attributes()["submitted_by"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSGroupGroupAuditAccount(data *groupGroupAuditAccountDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.AccountUUID = obj.Attributes()["account_uuid"].(basetypes.StringValue)
	data.AccountValid = obj.Attributes()["account_valid"].(basetypes.BoolValue)
	data.Action = obj.Attributes()["action"].(basetypes.StringValue)
	data.Comment = obj.Attributes()["comment"].(basetypes.StringValue)
	data.DisconnectedNested = obj.Attributes()["disconnected_nested"].(basetypes.BoolValue)
	data.DisplayName = obj.Attributes()["display_name"].(basetypes.StringValue)
	data.EndDate = obj.Attributes()["end_date"].(basetypes.StringValue)
	data.LastActive = obj.Attributes()["last_active"].(basetypes.StringValue)
	data.LastUsed = obj.Attributes()["last_used"].(basetypes.StringValue)
	data.Nested = obj.Attributes()["nested"].(basetypes.BoolValue)
	data.Rights = obj.Attributes()["rights"].(basetypes.StringValue)
	data.Username = obj.Attributes()["username"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSGroupGroupAuditConfig(data *groupGroupAuditConfigDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Months = obj.Attributes()["months"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSGroupGroupAuditLinkableWrapper(data *groupGroupAuditLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSGroupGroupAudit_additionalObjects(data *groupGroupAudit_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSGroupGroupAuditingInfo(data *groupGroupAuditingInfoDataRS, obj types.Object) {
	data.AuditDueDate = obj.Attributes()["audit_due_date"].(basetypes.StringValue)
	data.LastAuditDate = obj.Attributes()["last_audit_date"].(basetypes.StringValue)
	data.NrAccounts = obj.Attributes()["nr_accounts"].(basetypes.Int64Value)
	data.NrDisabledAccounts = obj.Attributes()["nr_disabled_accounts"].(basetypes.Int64Value)
	data.NrDisabledManagers = obj.Attributes()["nr_disabled_managers"].(basetypes.Int64Value)
	data.NrExpiredVaultRecords = obj.Attributes()["nr_expired_vault_records"].(basetypes.Int64Value)
	data.NrManagers = obj.Attributes()["nr_managers"].(basetypes.Int64Value)
	data.NrVaultRecordsWithEndDate = obj.Attributes()["nr_vault_records_with_end_date"].(basetypes.Int64Value)
}

func fillDataStructFromTFObjectRSGroupGroupClassificationPrimer(data *groupGroupClassificationPrimerDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSGroupGroupClient(data *groupGroupClientDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.ActivationRequired = obj.Attributes()["activation_required"].(basetypes.BoolValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.ClientUUID = obj.Attributes()["client_uuid"].(basetypes.StringValue)
	data.GroupUUID = obj.Attributes()["group_uuid"].(basetypes.StringValue)
	data.OwnerUUID = obj.Attributes()["owner_uuid"].(basetypes.StringValue)
	data.TechnicalAdministratorUUID = obj.Attributes()["technical_administrator_uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSGroupGroupClientLinkableWrapper(data *groupGroupClientLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSGroupGroupClient_additionalObjects(data *groupGroupClient_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSGroupGroupInfo(data *groupGroupInfoDataRS, obj types.Object) {
	data.NrAccounts = obj.Attributes()["nr_accounts"].(basetypes.Int64Value)
	data.NrAccountsWithVault = obj.Attributes()["nr_accounts_with_vault"].(basetypes.Int64Value)
	data.NrAudits = obj.Attributes()["nr_audits"].(basetypes.Int64Value)
	data.NrClients = obj.Attributes()["nr_clients"].(basetypes.Int64Value)
	data.NrProvisionedSystems = obj.Attributes()["nr_provisioned_systems"].(basetypes.Int64Value)
	data.NrVaultRecords = obj.Attributes()["nr_vault_records"].(basetypes.Int64Value)
}

func fillDataStructFromTFObjectRSGroupGroupLinkableWrapper(data *groupGroupLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSGroupGroupPrimer(data *groupGroupPrimerDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Admin = obj.Attributes()["admin"].(basetypes.BoolValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.OrganizationalUnitUUID = obj.Attributes()["organizational_unit_uuid"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSGroupGroupPrimerLinkableWrapper(data *groupGroupPrimerLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSGroupGroup_additionalObjects(data *groupGroup_additionalObjectsDataRS, obj types.Object) {
	data.Accounts = obj.Attributes()["accounts"].(basetypes.ListValue)
	data.AdministeredClients = obj.Attributes()["administered_clients"].(basetypes.ListValue)
	data.AdministeredSystems = obj.Attributes()["administered_systems"].(basetypes.ListValue)
	data.Admins = obj.Attributes()["admins"].(basetypes.ListValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.AuthorizedGroups = obj.Attributes()["authorized_groups"].(basetypes.ObjectValue)
	data.ClientPermissions = obj.Attributes()["client_permissions"].(basetypes.ListValue)
	data.Clients = obj.Attributes()["clients"].(basetypes.ListValue)
	data.ContentAdministeredSystems = obj.Attributes()["content_administered_systems"].(basetypes.ListValue)
	data.Groupauditinginfo = obj.Attributes()["groupauditinginfo"].(basetypes.ObjectValue)
	data.Groupinfo = obj.Attributes()["groupinfo"].(basetypes.ObjectValue)
	data.Helpdesk = obj.Attributes()["helpdesk"].(basetypes.ListValue)
	data.Markers = obj.Attributes()["markers"].(basetypes.ObjectValue)
	data.Myaccount = obj.Attributes()["myaccount"].(basetypes.ObjectValue)
	data.Mydelegatedaccount = obj.Attributes()["mydelegatedaccount"].(basetypes.ObjectValue)
	data.NestedGroups = obj.Attributes()["nested_groups"].(basetypes.ListValue)
	data.OwnedClients = obj.Attributes()["owned_clients"].(basetypes.ListValue)
	data.OwnedDirectories = obj.Attributes()["owned_directories"].(basetypes.ListValue)
	data.OwnedGroupsOnSystem = obj.Attributes()["owned_groups_on_system"].(basetypes.ObjectValue)
	data.OwnedOrganizationalUnits = obj.Attributes()["owned_organizational_units"].(basetypes.ListValue)
	data.OwnedSystems = obj.Attributes()["owned_systems"].(basetypes.ListValue)
	data.RecentAudits = obj.Attributes()["recent_audits"].(basetypes.ListValue)
	data.Requeststatus = obj.Attributes()["requeststatus"].(basetypes.StringValue)
	data.ServiceAccounts = obj.Attributes()["service_accounts"].(basetypes.ListValue)
	data.Systems = obj.Attributes()["systems"].(basetypes.ListValue)
	data.Vault = obj.Attributes()["vault"].(basetypes.ObjectValue)
	data.Webhooks = obj.Attributes()["webhooks"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSGroupProvisioningGroup(data *groupProvisioningGroupDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.ActivationRequired = obj.Attributes()["activation_required"].(basetypes.BoolValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.GroupUUID = obj.Attributes()["group_uuid"].(basetypes.StringValue)
	data.GroupOnSystem = obj.Attributes()["group_on_system"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSGroupProvisioningGroupLinkableWrapper(data *groupProvisioningGroupLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSGroupProvisioningGroup_additionalObjects(data *groupProvisioningGroup_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSGroupVaultVaultRecord(data *groupVaultVaultRecordDataRS, obj types.Object) {
	data.GroupUUID = obj.Attributes()["group_uuid"].(basetypes.StringValue)
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Color = obj.Attributes()["color"].(basetypes.StringValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.ShareEndTime = obj.Attributes()["share_end_time"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.DeleteTile = obj.Attributes()["delete_tile"].(basetypes.BoolValue)
	data.ParentUUID = obj.Attributes()["parent_uuid"].(basetypes.StringValue)
	data.PasswordMetadata = obj.Attributes()["password_metadata"].(basetypes.ObjectValue)
	data.Secret = obj.Attributes()["secret"].(basetypes.ObjectValue)
	data.ShareSummary = obj.Attributes()["share_summary"].(basetypes.ObjectValue)
	data.Shares = obj.Attributes()["shares"].(basetypes.ListValue)
	data.Tile = obj.Attributes()["tile"].(basetypes.ObjectValue)
	data.Vaultholder = obj.Attributes()["vaultholder"].(basetypes.ObjectValue)
	data.Derived = obj.Attributes()["derived"].(basetypes.BoolValue)
	data.EndDate = obj.Attributes()["end_date"].(basetypes.StringValue)
	data.Filename = obj.Attributes()["filename"].(basetypes.StringValue)
	data.Types = obj.Attributes()["types"].(basetypes.ListValue)
	data.URL = obj.Attributes()["url"].(basetypes.StringValue)
	data.Username = obj.Attributes()["username"].(basetypes.StringValue)
	data.WarningPeriod = obj.Attributes()["warning_period"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSLaunchpadSsoApplicationLaunchpadTile(data *launchpadSsoApplicationLaunchpadTileDataRS, obj types.Object) {
	data.URI = obj.Attributes()["uri"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSLaunchpadVaultRecordLaunchpadTile(data *launchpadVaultRecordLaunchpadTileDataRS, obj types.Object) {
}

func fillDataStructFromTFObjectRSMarkItemMarker(data *markItemMarkerDataRS, obj types.Object) {
	data.Level = obj.Attributes()["level"].(basetypes.StringValue)
	data.MarkItemMarkerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.Parameters = obj.Attributes()["parameters"].(basetypes.MapValue)
}

func fillDataStructFromTFObjectRSMarkItemMarkers(data *markItemMarkersDataRS, obj types.Object) {
	data.Markers = obj.Attributes()["markers"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSNestedProvisioningGroupOnSystem(data *nestedProvisioningGroupOnSystemDataRS, obj types.Object) {
	data.ProvisionedSystemUUID = obj.Attributes()["provisioned_system_uuid"].(basetypes.StringValue)
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.DisplayName = obj.Attributes()["display_name"].(basetypes.StringValue)
	data.NameInSystem = obj.Attributes()["name_in_system"].(basetypes.StringValue)
	data.ProvisioningGroupOnSystemPrimerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.ShortNameInSystem = obj.Attributes()["short_name_in_system"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.Provgroups = obj.Attributes()["provgroups"].(basetypes.ListValue)
	data.ServiceAccounts = obj.Attributes()["service_accounts"].(basetypes.ListValue)
	data.OwnerUUID = obj.Attributes()["owner_uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSOrganizationOrganizationalUnit(data *organizationOrganizationalUnitDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.CreateAsParentOf = obj.Attributes()["create_as_parent_of"].(basetypes.ListValue)
	data.Depth = obj.Attributes()["depth"].(basetypes.Int64Value)
	data.Description = obj.Attributes()["description"].(basetypes.StringValue)
	data.OwnerUUID = obj.Attributes()["owner_uuid"].(basetypes.StringValue)
	data.ParentUUID = obj.Attributes()["parent_uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSOrganizationOrganizationalUnitLinkableWrapper(data *organizationOrganizationalUnitLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSOrganizationOrganizationalUnitPrimer(data *organizationOrganizationalUnitPrimerDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSOrganizationOrganizationalUnitPrimerLinkableWrapper(data *organizationOrganizationalUnitPrimerLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSOrganizationOrganizationalUnit_additionalObjects(data *organizationOrganizationalUnit_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.CreateAsParentOf = obj.Attributes()["create_as_parent_of"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSProvisioningAbstractProvisionedLDAP(data *provisioningAbstractProvisionedLDAPDataRS, obj types.Object) {
	data.Attributes = obj.Attributes()["attributes"].(basetypes.MapValue)
	data.BaseDN = obj.Attributes()["base_dn"].(basetypes.StringValue)
	data.BindDN = obj.Attributes()["bind_dn"].(basetypes.StringValue)
	data.BindPassword = obj.Attributes()["bind_password"].(basetypes.StringValue)
	data.ClientCertificateUUID = obj.Attributes()["client_certificate_uuid"].(basetypes.StringValue)
	data.FailoverHost = obj.Attributes()["failover_host"].(basetypes.StringValue)
	data.FailoverTrustedCertificateUUID = obj.Attributes()["failover_trusted_certificate_uuid"].(basetypes.StringValue)
	data.GroupDN = obj.Attributes()["group_dn"].(basetypes.StringValue)
	data.Host = obj.Attributes()["host"].(basetypes.StringValue)
	data.ObjectClasses = obj.Attributes()["object_classes"].(basetypes.StringValue)
	data.Port = obj.Attributes()["port"].(basetypes.Int64Value)
	data.ServiceAccountDN = obj.Attributes()["service_account_dn"].(basetypes.StringValue)
	data.SshPublicKeySupported = obj.Attributes()["ssh_public_key_supported"].(basetypes.BoolValue)
	data.TLS = obj.Attributes()["tls"].(basetypes.StringValue)
	data.TrustedCertificateUUID = obj.Attributes()["trusted_certificate_uuid"].(basetypes.StringValue)
	data.UserDN = obj.Attributes()["user_dn"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningCircuitBreakerStatistics(data *provisioningCircuitBreakerStatisticsDataRS, obj types.Object) {
	data.NumberOfFailedCalls = obj.Attributes()["number_of_failed_calls"].(basetypes.Int64Value)
	data.NumberOfNotPermittedCalls = obj.Attributes()["number_of_not_permitted_calls"].(basetypes.Int64Value)
	data.NumberOfSuccessfulCalls = obj.Attributes()["number_of_successful_calls"].(basetypes.Int64Value)
	data.State = obj.Attributes()["state"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningGroupOnSystem(data *provisioningGroupOnSystemDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.DisplayName = obj.Attributes()["display_name"].(basetypes.StringValue)
	data.NameInSystem = obj.Attributes()["name_in_system"].(basetypes.StringValue)
	data.ProvisioningGroupOnSystemPrimerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.ShortNameInSystem = obj.Attributes()["short_name_in_system"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.Provgroups = obj.Attributes()["provgroups"].(basetypes.ListValue)
	data.ServiceAccounts = obj.Attributes()["service_accounts"].(basetypes.ListValue)
	data.OwnerUUID = obj.Attributes()["owner_uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningGroupOnSystemLinkableWrapper(data *provisioningGroupOnSystemLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSProvisioningGroupOnSystemPrimer(data *provisioningGroupOnSystemPrimerDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.DisplayName = obj.Attributes()["display_name"].(basetypes.StringValue)
	data.NameInSystem = obj.Attributes()["name_in_system"].(basetypes.StringValue)
	data.ProvisioningGroupOnSystemPrimerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.ShortNameInSystem = obj.Attributes()["short_name_in_system"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningGroupOnSystemTypes(data *provisioningGroupOnSystemTypesDataRS, obj types.Object) {
	data.Types = obj.Attributes()["types"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSProvisioningGroupOnSystem_additionalObjects(data *provisioningGroupOnSystem_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.Provgroups = obj.Attributes()["provgroups"].(basetypes.ListValue)
	data.ServiceAccounts = obj.Attributes()["service_accounts"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSProvisioningOwnedGroupOnSystemsWrapper(data *provisioningOwnedGroupOnSystemsWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
	data.UnlinkedCount = obj.Attributes()["unlinked_count"].(basetypes.Int64Value)
}

func fillDataStructFromTFObjectRSProvisioningProvisionNumberSequence(data *provisioningProvisionNumberSequenceDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.AccountCount = obj.Attributes()["account_count"].(basetypes.Int64Value)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.Systems = obj.Attributes()["systems"].(basetypes.ListValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.NextUID = obj.Attributes()["next_uid"].(basetypes.Int64Value)
}

func fillDataStructFromTFObjectRSProvisioningProvisionNumberSequence_additionalObjects(data *provisioningProvisionNumberSequence_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.Systems = obj.Attributes()["systems"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedAD(data *provisioningProvisionedADDataRS, obj types.Object) {
	data.SamAccountNameScheme = obj.Attributes()["sam_account_name_scheme"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedAccount(data *provisioningProvisionedAccountDataRS, obj types.Object) {
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.UID = obj.Attributes()["uid"].(basetypes.Int64Value)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedAccount_additionalObjects(data *provisioningProvisionedAccount_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedAzureOIDCDirectory(data *provisioningProvisionedAzureOIDCDirectoryDataRS, obj types.Object) {
	data.DirectoryUUID = obj.Attributes()["directory_uuid"].(basetypes.StringValue)
	data.Tenant = obj.Attributes()["tenant"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedAzureSyncLDAPDirectory(data *provisioningProvisionedAzureSyncLDAPDirectoryDataRS, obj types.Object) {
	data.ClientID = obj.Attributes()["client_id"].(basetypes.StringValue)
	data.ClientSecret = obj.Attributes()["client_secret"].(basetypes.StringValue)
	data.DirectoryUUID = obj.Attributes()["directory_uuid"].(basetypes.StringValue)
	data.Tenant = obj.Attributes()["tenant"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedAzureTenant(data *provisioningProvisionedAzureTenantDataRS, obj types.Object) {
	data.ClientID = obj.Attributes()["client_id"].(basetypes.StringValue)
	data.ClientSecret = obj.Attributes()["client_secret"].(basetypes.StringValue)
	data.IDpDomain = obj.Attributes()["idp_domain"].(basetypes.StringValue)
	data.Tenant = obj.Attributes()["tenant"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedInternalLDAP(data *provisioningProvisionedInternalLDAPDataRS, obj types.Object) {
	data.ClientUUID = obj.Attributes()["client_uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedLDAP(data *provisioningProvisionedLDAPDataRS, obj types.Object) {
	data.Gid = obj.Attributes()["gid"].(basetypes.Int64Value)
	data.HashingScheme = obj.Attributes()["hashing_scheme"].(basetypes.StringValue)
	data.Numbering = obj.Attributes()["numbering"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedLDAPDirectory(data *provisioningProvisionedLDAPDirectoryDataRS, obj types.Object) {
	data.DirectoryUUID = obj.Attributes()["directory_uuid"].(basetypes.StringValue)
	data.GroupDN = obj.Attributes()["group_dn"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedNamespace(data *provisioningProvisionedNamespaceDataRS, obj types.Object) {
	data.BaseSystemUUID = obj.Attributes()["base_system_uuid"].(basetypes.StringValue)
	data.GroupDN = obj.Attributes()["group_dn"].(basetypes.StringValue)
	data.ServiceAccountDN = obj.Attributes()["service_account_dn"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedSystem(data *provisioningProvisionedSystemDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Active = obj.Attributes()["active"].(basetypes.BoolValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.OrganizationalUnitUUID = obj.Attributes()["organizational_unit_uuid"].(basetypes.StringValue)
	data.ProvisioningProvisionedSystemPrimerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.AccountCount = obj.Attributes()["account_count"].(basetypes.Int64Value)
	data.Account = obj.Attributes()["account"].(basetypes.ObjectValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.IssuedPermissions = obj.Attributes()["issued_permissions"].(basetypes.ListValue)
	data.LoginName = obj.Attributes()["login_name"].(basetypes.StringValue)
	data.ManagementPermissions = obj.Attributes()["management_permissions"].(basetypes.ObjectValue)
	data.Markers = obj.Attributes()["markers"].(basetypes.ObjectValue)
	data.Statistics = obj.Attributes()["statistics"].(basetypes.ObjectValue)
	data.SupportedGroupTypes = obj.Attributes()["supported_group_types"].(basetypes.ObjectValue)
	data.ContentAdministratorUUID = obj.Attributes()["content_administrator_uuid"].(basetypes.StringValue)
	data.ExternalUUID = obj.Attributes()["external_uuid"].(basetypes.StringValue)
	data.OwnerUUID = obj.Attributes()["owner_uuid"].(basetypes.StringValue)
	data.SelfServiceExistingGroups = obj.Attributes()["self_service_existing_groups"].(basetypes.BoolValue)
	data.SelfServiceNewGroups = obj.Attributes()["self_service_new_groups"].(basetypes.BoolValue)
	data.SelfServiceNewNamespaces = obj.Attributes()["self_service_new_namespaces"].(basetypes.BoolValue)
	data.SelfServiceServiceAccounts = obj.Attributes()["self_service_service_accounts"].(basetypes.BoolValue)
	data.ShouldDestroyUnknownAccounts = obj.Attributes()["should_destroy_unknown_accounts"].(basetypes.BoolValue)
	data.TechnicalAdministratorUUID = obj.Attributes()["technical_administrator_uuid"].(basetypes.StringValue)
	data.UsernamePrefix = obj.Attributes()["username_prefix"].(basetypes.StringValue)
	data.AbstractProvisionedLDAP = obj.Attributes()["abstract_provisioned_ldap"].(basetypes.ObjectValue)
	data.ProvisionedAD = obj.Attributes()["provisioned_a_d"].(basetypes.ObjectValue)
	data.ProvisionedAzureOIDCDirectory = obj.Attributes()["provisioned_azure_oidc_directory"].(basetypes.ObjectValue)
	data.ProvisionedAzureSyncLDAPDirectory = obj.Attributes()["provisioned_azure_sync_ldap_directory"].(basetypes.ObjectValue)
	data.ProvisionedAzureTenant = obj.Attributes()["provisioned_azure_tenant"].(basetypes.ObjectValue)
	data.ProvisionedInternalLDAP = obj.Attributes()["provisioned_internal_ldap"].(basetypes.ObjectValue)
	data.ProvisionedLDAP = obj.Attributes()["provisioned_ldap"].(basetypes.ObjectValue)
	data.ProvisionedLDAPDirectory = obj.Attributes()["provisioned_ldap_directory"].(basetypes.ObjectValue)
	data.ProvisionedNamespace = obj.Attributes()["provisioned_namespace"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedSystemLinkableWrapper(data *provisioningProvisionedSystemLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedSystemPrimer(data *provisioningProvisionedSystemPrimerDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Active = obj.Attributes()["active"].(basetypes.BoolValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.OrganizationalUnitUUID = obj.Attributes()["organizational_unit_uuid"].(basetypes.StringValue)
	data.ProvisioningProvisionedSystemPrimerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedSystemPrimerLinkableWrapper(data *provisioningProvisionedSystemPrimerLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisionedSystem_additionalObjects(data *provisioningProvisionedSystem_additionalObjectsDataRS, obj types.Object) {
	data.Account = obj.Attributes()["account"].(basetypes.ObjectValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.IssuedPermissions = obj.Attributes()["issued_permissions"].(basetypes.ListValue)
	data.LoginName = obj.Attributes()["login_name"].(basetypes.StringValue)
	data.ManagementPermissions = obj.Attributes()["management_permissions"].(basetypes.ObjectValue)
	data.Markers = obj.Attributes()["markers"].(basetypes.ObjectValue)
	data.Statistics = obj.Attributes()["statistics"].(basetypes.ObjectValue)
	data.SupportedGroupTypes = obj.Attributes()["supported_group_types"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSProvisioningProvisioningManagementPermissions(data *provisioningProvisioningManagementPermissionsDataRS, obj types.Object) {
	data.CreateNewGroupsAllowed = obj.Attributes()["create_new_groups_allowed"].(basetypes.BoolValue)
	data.CreateServiceAccountsAllowed = obj.Attributes()["create_service_accounts_allowed"].(basetypes.BoolValue)
	data.ReuseExistingGroupsAllowed = obj.Attributes()["reuse_existing_groups_allowed"].(basetypes.BoolValue)
}

func fillDataStructFromTFObjectRSServiceaccountServiceAccount(data *serviceaccountServiceAccountDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Active = obj.Attributes()["active"].(basetypes.BoolValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.SystemUUID = obj.Attributes()["system_uuid"].(basetypes.StringValue)
	data.Username = obj.Attributes()["username"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.Groups = obj.Attributes()["groups"].(basetypes.ListValue)
	data.Secret = obj.Attributes()["secret"].(basetypes.ObjectValue)
	data.Description = obj.Attributes()["description"].(basetypes.StringValue)
	data.PasswordUUID = obj.Attributes()["password_uuid"].(basetypes.StringValue)
	data.PasswordRotation = obj.Attributes()["password_rotation"].(basetypes.StringValue)
	data.TechnicalAdministratorUUID = obj.Attributes()["technical_administrator_uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSServiceaccountServiceAccountGroup(data *serviceaccountServiceAccountGroupDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.DisplayName = obj.Attributes()["display_name"].(basetypes.StringValue)
	data.NameInSystem = obj.Attributes()["name_in_system"].(basetypes.StringValue)
	data.ProvisioningGroupOnSystemPrimerType = obj.Attributes()["type"].(basetypes.StringValue)
	data.ShortNameInSystem = obj.Attributes()["short_name_in_system"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSServiceaccountServiceAccountGroupLinkableWrapper(data *serviceaccountServiceAccountGroupLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSServiceaccountServiceAccountGroup_additionalObjects(data *serviceaccountServiceAccountGroup_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSServiceaccountServiceAccountLinkableWrapper(data *serviceaccountServiceAccountLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSServiceaccountServiceAccountPrimer(data *serviceaccountServiceAccountPrimerDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Active = obj.Attributes()["active"].(basetypes.BoolValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.SystemUUID = obj.Attributes()["system_uuid"].(basetypes.StringValue)
	data.Username = obj.Attributes()["username"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSServiceaccountServiceAccountPrimerLinkableWrapper(data *serviceaccountServiceAccountPrimerLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSServiceaccountServiceAccount_additionalObjects(data *serviceaccountServiceAccount_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.Groups = obj.Attributes()["groups"].(basetypes.ListValue)
	data.Secret = obj.Attributes()["secret"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSVaultPasswordMetadata(data *vaultPasswordMetadataDataRS, obj types.Object) {
	data.Dictionary = obj.Attributes()["dictionary"].(basetypes.BoolValue)
	data.Duplicate = obj.Attributes()["duplicate"].(basetypes.BoolValue)
	data.Hash = obj.Attributes()["hash"].(basetypes.StringValue)
	data.Length = obj.Attributes()["length"].(basetypes.Int64Value)
	data.LowerCount = obj.Attributes()["lower_count"].(basetypes.Int64Value)
	data.NumberCount = obj.Attributes()["number_count"].(basetypes.Int64Value)
	data.SpecialCount = obj.Attributes()["special_count"].(basetypes.Int64Value)
	data.Strength = obj.Attributes()["strength"].(basetypes.Int64Value)
	data.UpperCount = obj.Attributes()["upper_count"].(basetypes.Int64Value)
}

func fillDataStructFromTFObjectRSVaultVault(data *vaultVaultDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.AccessAvailable = obj.Attributes()["access_available"].(basetypes.BoolValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.Records = obj.Attributes()["records"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSVaultVaultHolder(data *vaultVaultHolderDataRS, obj types.Object) {
}

func fillDataStructFromTFObjectRSVaultVaultRecord(data *vaultVaultRecordDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Color = obj.Attributes()["color"].(basetypes.StringValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.ShareEndTime = obj.Attributes()["share_end_time"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.DeleteTile = obj.Attributes()["delete_tile"].(basetypes.BoolValue)
	data.ParentUUID = obj.Attributes()["parent_uuid"].(basetypes.StringValue)
	data.PasswordMetadata = obj.Attributes()["password_metadata"].(basetypes.ObjectValue)
	data.Secret = obj.Attributes()["secret"].(basetypes.ObjectValue)
	data.ShareSummary = obj.Attributes()["share_summary"].(basetypes.ObjectValue)
	data.Shares = obj.Attributes()["shares"].(basetypes.ListValue)
	data.Tile = obj.Attributes()["tile"].(basetypes.ObjectValue)
	data.Vaultholder = obj.Attributes()["vaultholder"].(basetypes.ObjectValue)
	data.Derived = obj.Attributes()["derived"].(basetypes.BoolValue)
	data.EndDate = obj.Attributes()["end_date"].(basetypes.StringValue)
	data.Filename = obj.Attributes()["filename"].(basetypes.StringValue)
	data.Types = obj.Attributes()["types"].(basetypes.ListValue)
	data.URL = obj.Attributes()["url"].(basetypes.StringValue)
	data.Username = obj.Attributes()["username"].(basetypes.StringValue)
	data.WarningPeriod = obj.Attributes()["warning_period"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSVaultVaultRecordPrimer(data *vaultVaultRecordPrimerDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.Color = obj.Attributes()["color"].(basetypes.StringValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.ShareEndTime = obj.Attributes()["share_end_time"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSVaultVaultRecordPrimerLinkableWrapper(data *vaultVaultRecordPrimerLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSVaultVaultRecordSecrets(data *vaultVaultRecordSecretsDataRS, obj types.Object) {
	data.Comment = obj.Attributes()["comment"].(basetypes.StringValue)
	data.File = obj.Attributes()["file"].(basetypes.StringValue)
	data.Password = obj.Attributes()["password"].(basetypes.StringValue)
	data.Totp = obj.Attributes()["totp"].(basetypes.StringValue)
	data.WriteTotp = obj.Attributes()["write_totp"].(basetypes.BoolValue)
}

func fillDataStructFromTFObjectRSVaultVaultRecordShare(data *vaultVaultRecordShareDataRS, obj types.Object) {
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.VaultVaultRecordShareType = obj.Attributes()["type"].(basetypes.StringValue)
}

func fillDataStructFromTFObjectRSVaultVaultRecordShareSummary(data *vaultVaultRecordShareSummaryDataRS, obj types.Object) {
	data.Children = obj.Attributes()["children"].(basetypes.ListValue)
	data.Parent = obj.Attributes()["parent"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSVaultVaultRecord_additionalObjects(data *vaultVaultRecord_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.DeleteTile = obj.Attributes()["delete_tile"].(basetypes.BoolValue)
	data.ParentUUID = obj.Attributes()["parent_uuid"].(basetypes.StringValue)
	data.PasswordMetadata = obj.Attributes()["password_metadata"].(basetypes.ObjectValue)
	data.Secret = obj.Attributes()["secret"].(basetypes.ObjectValue)
	data.ShareSummary = obj.Attributes()["share_summary"].(basetypes.ObjectValue)
	data.Shares = obj.Attributes()["shares"].(basetypes.ListValue)
	data.Tile = obj.Attributes()["tile"].(basetypes.ObjectValue)
	data.Vaultholder = obj.Attributes()["vaultholder"].(basetypes.ObjectValue)
}

func fillDataStructFromTFObjectRSWebhookWebhook(data *webhookWebhookDataRS, obj types.Object) {
	data.Links = obj.Attributes()["links"].(basetypes.ListValue)
	data.Permissions = obj.Attributes()["permissions"].(basetypes.ListValue)
	data.AccountUUID = obj.Attributes()["account_uuid"].(basetypes.StringValue)
	data.Active = obj.Attributes()["active"].(basetypes.BoolValue)
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
	data.AllTypes = obj.Attributes()["all_types"].(basetypes.BoolValue)
	data.AuthenticationScheme = obj.Attributes()["authentication_scheme"].(basetypes.StringValue)
	data.BasicAuthPassword = obj.Attributes()["basic_auth_password"].(basetypes.StringValue)
	data.BasicAuthUsername = obj.Attributes()["basic_auth_username"].(basetypes.StringValue)
	data.BearerToken = obj.Attributes()["bearer_token"].(basetypes.StringValue)
	data.ClientUUID = obj.Attributes()["client_uuid"].(basetypes.StringValue)
	data.ClientCertificateUUID = obj.Attributes()["client_certificate_uuid"].(basetypes.StringValue)
	data.CustomHeaderName = obj.Attributes()["custom_header_name"].(basetypes.StringValue)
	data.CustomHeaderValue = obj.Attributes()["custom_header_value"].(basetypes.StringValue)
	data.DirectoryUUID = obj.Attributes()["directory_uuid"].(basetypes.StringValue)
	data.GroupUUID = obj.Attributes()["group_uuid"].(basetypes.StringValue)
	data.Name = obj.Attributes()["name"].(basetypes.StringValue)
	data.SystemUUID = obj.Attributes()["system_uuid"].(basetypes.StringValue)
	data.TLS = obj.Attributes()["tls"].(basetypes.StringValue)
	data.TrustedCertificateUUID = obj.Attributes()["trusted_certificate_uuid"].(basetypes.StringValue)
	data.Types = obj.Attributes()["types"].(basetypes.ListValue)
	data.URL = obj.Attributes()["url"].(basetypes.StringValue)
	data.UUID = obj.Attributes()["uuid"].(basetypes.StringValue)
	data.VerbosePayloads = obj.Attributes()["verbose_payloads"].(basetypes.BoolValue)
}

func fillDataStructFromTFObjectRSWebhookWebhookLinkableWrapper(data *webhookWebhookLinkableWrapperDataRS, obj types.Object) {
	data.Items = obj.Attributes()["items"].(basetypes.ListValue)
}

func fillDataStructFromTFObjectRSWebhookWebhook_additionalObjects(data *webhookWebhook_additionalObjectsDataRS, obj types.Object) {
	data.Audit = obj.Attributes()["audit"].(basetypes.ObjectValue)
}
