// Code generated by "terraform-provider-keyhub-generator"; DO NOT EDIT.
// Copyright (c) Topicus Security B.V.
// SPDX-License-Identifier: APSL-2.0

//lint:ignore U1000 Ignore unused functions in generated code
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var auditInfoAttrTypesDS = objectAttrsTypeDSAuditInfo(false)
var auditInfoAttrTypesDSRecurse = objectAttrsTypeDSAuditInfo(true)

type auditInfoDataDS struct {
	CreatedAt      types.String `tfsdk:"created_at"`
	CreatedBy      types.String `tfsdk:"created_by"`
	LastModifiedAt types.String `tfsdk:"last_modified_at"`
	LastModifiedBy types.String `tfsdk:"last_modified_by"`
}

var generatedSecretAttrTypesDS = objectAttrsTypeDSGeneratedSecret(false)
var generatedSecretAttrTypesDSRecurse = objectAttrsTypeDSGeneratedSecret(true)

type generatedSecretDataDS struct {
	GeneratedSecret types.String `tfsdk:"generated_secret"`
}

var linkableAttrTypesDS = objectAttrsTypeDSLinkable(false)
var linkableAttrTypesDSRecurse = objectAttrsTypeDSLinkable(true)

type linkableDataDS struct {
	Links       types.Set `tfsdk:"links"`
	Permissions types.Set `tfsdk:"permissions"`
}

var nonLinkableAttrTypesDS = objectAttrsTypeDSNonLinkable(false)
var nonLinkableAttrTypesDSRecurse = objectAttrsTypeDSNonLinkable(true)

type nonLinkableDataDS struct {
}

var restLinkAttrTypesDS = objectAttrsTypeDSRestLink(false)
var restLinkAttrTypesDSRecurse = objectAttrsTypeDSRestLink(true)

type restLinkDataDS struct {
	Href        types.String `tfsdk:"href"`
	ID          types.Int64  `tfsdk:"id"`
	Rel         types.String `tfsdk:"rel"`
	TypeEscaped types.String `tfsdk:"type_escaped"`
}

var auditGroupAuditAttrTypesDS = objectAttrsTypeDSAuditGroupAudit(false)
var auditGroupAuditAttrTypesDSRecurse = objectAttrsTypeDSAuditGroupAudit(true)

type auditGroupAuditDataDS struct {
	Links        types.Set    `tfsdk:"links"`
	Permissions  types.Set    `tfsdk:"permissions"`
	Additional   types.List   `tfsdk:"additional"`
	Accounts     types.Set    `tfsdk:"accounts"`
	Audit        types.Object `tfsdk:"audit" tkhao:"audit"`
	Comment      types.String `tfsdk:"comment"`
	CreatedAt    types.String `tfsdk:"created_at"`
	CreatedBy    types.String `tfsdk:"created_by"`
	GroupName    types.String `tfsdk:"group_name"`
	NameOnAudit  types.String `tfsdk:"name_on_audit"`
	NestedGroups types.Set    `tfsdk:"nested_groups"`
	ReviewedAt   types.String `tfsdk:"reviewed_at"`
	ReviewedBy   types.String `tfsdk:"reviewed_by"`
	Status       types.String `tfsdk:"status"`
	SubmittedAt  types.String `tfsdk:"submitted_at"`
	SubmittedBy  types.String `tfsdk:"submitted_by"`
}

var auditGroupAuditAccountAttrTypesDS = objectAttrsTypeDSAuditGroupAuditAccount(false)
var auditGroupAuditAccountAttrTypesDSRecurse = objectAttrsTypeDSAuditGroupAuditAccount(true)

type auditGroupAuditAccountDataDS struct {
	Links              types.Set    `tfsdk:"links"`
	Permissions        types.Set    `tfsdk:"permissions"`
	AccountUUID        types.String `tfsdk:"account_uuid"`
	AccountValid       types.Bool   `tfsdk:"account_valid"`
	Action             types.String `tfsdk:"action"`
	Comment            types.String `tfsdk:"comment"`
	DisconnectedNested types.Bool   `tfsdk:"disconnected_nested"`
	DisplayName        types.String `tfsdk:"display_name"`
	EndDate            types.String `tfsdk:"end_date"`
	LastActive         types.String `tfsdk:"last_active"`
	LastUsed           types.String `tfsdk:"last_used"`
	Nested             types.Bool   `tfsdk:"nested"`
	Rights             types.String `tfsdk:"rights"`
	Username           types.String `tfsdk:"username"`
}

var auditGroupAuditLinkableWrapperAttrTypesDS = objectAttrsTypeDSAuditGroupAuditLinkableWrapper(false)
var auditGroupAuditLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSAuditGroupAuditLinkableWrapper(true)

type auditGroupAuditLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var auditGroupAudit_additionalObjectsAttrTypesDS = objectAttrsTypeDSAuditGroupAudit_additionalObjects(false)
var auditGroupAudit_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSAuditGroupAudit_additionalObjects(true)

type auditGroupAudit_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
}

var auditNestedGroupAuditAttrTypesDS = objectAttrsTypeDSAuditNestedGroupAudit(false)
var auditNestedGroupAuditAttrTypesDSRecurse = objectAttrsTypeDSAuditNestedGroupAudit(true)

type auditNestedGroupAuditDataDS struct {
	Links       types.Set    `tfsdk:"links"`
	Permissions types.Set    `tfsdk:"permissions"`
	Action      types.String `tfsdk:"action"`
	Comment     types.String `tfsdk:"comment"`
	GroupUUID   types.String `tfsdk:"group_uuid"`
	Name        types.String `tfsdk:"name"`
}

var authAccountAttrTypesDS = objectAttrsTypeDSAuthAccount(false)
var authAccountAttrTypesDSRecurse = objectAttrsTypeDSAuthAccount(true)

type authAccountDataDS struct {
	Links                           types.Set    `tfsdk:"links"`
	Permissions                     types.Set    `tfsdk:"permissions"`
	DisplayName                     types.String `tfsdk:"display_name"`
	LastActive                      types.String `tfsdk:"last_active"`
	Username                        types.String `tfsdk:"username"`
	UUID                            types.String `tfsdk:"uuid"`
	Validity                        types.String `tfsdk:"validity"`
	Additional                      types.List   `tfsdk:"additional"`
	AccountPermissions              types.Set    `tfsdk:"account_permissions"`
	Active                          types.Bool   `tfsdk:"active"`
	ActiveLogin                     types.Bool   `tfsdk:"active_login" tkhao:"activeLogin"`
	Audit                           types.Object `tfsdk:"audit" tkhao:"audit"`
	Groups                          types.List   `tfsdk:"groups" tkhao:"groups"`
	PendingRecoveryRequests         types.Object `tfsdk:"pending_recovery_requests" tkhao:"pendingRecoveryRequests"`
	Settings                        types.Object `tfsdk:"settings" tkhao:"settings"`
	StoredAttributes                types.Object `tfsdk:"stored_attributes" tkhao:"storedAttributes"`
	Vault                           types.Object `tfsdk:"vault" tkhao:"vault"`
	CanRequestGroups                types.Bool   `tfsdk:"can_request_groups"`
	Directory                       types.Object `tfsdk:"directory"`
	DirectoryName                   types.String `tfsdk:"directory_name"`
	DirectoryPasswordChangeRequired types.Bool   `tfsdk:"directory_password_change_required"`
	DirectoryRotatingPassword       types.String `tfsdk:"directory_rotating_password"`
	DirectoryType                   types.String `tfsdk:"directory_type"`
	Email                           types.String `tfsdk:"email"`
	IDInDirectory                   types.String `tfsdk:"id_in_directory"`
	KeyHubPasswordChangeRequired    types.Bool   `tfsdk:"key_hub_password_change_required"`
	LastModifiedAt                  types.String `tfsdk:"last_modified_at"`
	LicenseRole                     types.String `tfsdk:"license_role"`
	Locale                          types.String `tfsdk:"locale"`
	ReregistrationRequired          types.Bool   `tfsdk:"reregistration_required"`
	TokenPasswordEnabled            types.Bool   `tfsdk:"token_password_enabled"`
	TwoFactorStatus                 types.String `tfsdk:"two_factor_status"`
	ValidInDirectory                types.Bool   `tfsdk:"valid_in_directory"`
}

var authAccountPrimerAttrTypesDS = objectAttrsTypeDSAuthAccountPrimer(false)
var authAccountPrimerAttrTypesDSRecurse = objectAttrsTypeDSAuthAccountPrimer(true)

type authAccountPrimerDataDS struct {
	Links       types.Set    `tfsdk:"links"`
	Permissions types.Set    `tfsdk:"permissions"`
	DisplayName types.String `tfsdk:"display_name"`
	LastActive  types.String `tfsdk:"last_active"`
	Username    types.String `tfsdk:"username"`
	UUID        types.String `tfsdk:"uuid"`
	Validity    types.String `tfsdk:"validity"`
}

var authAccountRecoveryStatusAttrTypesDS = objectAttrsTypeDSAuthAccountRecoveryStatus(false)
var authAccountRecoveryStatusAttrTypesDSRecurse = objectAttrsTypeDSAuthAccountRecoveryStatus(true)

type authAccountRecoveryStatusDataDS struct {
	Pending2FARecoveryRequest      types.Bool `tfsdk:"pending2fa_recovery_request"`
	PendingPasswordRecoveryRequest types.Bool `tfsdk:"pending_password_recovery_request"`
}

var authAccountSettingsAttrTypesDS = objectAttrsTypeDSAuthAccountSettings(false)
var authAccountSettingsAttrTypesDSRecurse = objectAttrsTypeDSAuthAccountSettings(true)

type authAccountSettingsDataDS struct {
	DefaultOrganizationalUnit        types.Object `tfsdk:"default_organizational_unit"`
	DirectoryName                    types.String `tfsdk:"directory_name"`
	DirectoryType                    types.String `tfsdk:"directory_type"`
	InGroups                         types.Bool   `tfsdk:"in_groups"`
	InMultipleOrganizationalUnits    types.Bool   `tfsdk:"in_multiple_organizational_units"`
	KeyHubAdmin                      types.Bool   `tfsdk:"key_hub_admin"`
	MultipleOrganizationalUnitsExist types.Bool   `tfsdk:"multiple_organizational_units_exist"`
	PasswordMode                     types.String `tfsdk:"password_mode"`
	SshPublicKey                     types.String `tfsdk:"ssh_public_key"`
	TwoFactorAuthentication          types.String `tfsdk:"two_factor_authentication"`
	UseTokenPassword                 types.Bool   `tfsdk:"use_token_password"`
	VaultStatus                      types.String `tfsdk:"vault_status"`
}

var authAccount_additionalObjectsAttrTypesDS = objectAttrsTypeDSAuthAccount_additionalObjects(false)
var authAccount_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSAuthAccount_additionalObjects(true)

type authAccount_additionalObjectsDataDS struct {
	ActiveLogin             types.Bool   `tfsdk:"active_login"`
	Audit                   types.Object `tfsdk:"audit"`
	Groups                  types.List   `tfsdk:"groups"`
	PendingRecoveryRequests types.Object `tfsdk:"pending_recovery_requests"`
	Settings                types.Object `tfsdk:"settings"`
	StoredAttributes        types.Object `tfsdk:"stored_attributes"`
	Vault                   types.Object `tfsdk:"vault"`
}

var authPermissionAttrTypesDS = objectAttrsTypeDSAuthPermission(false)
var authPermissionAttrTypesDSRecurse = objectAttrsTypeDSAuthPermission(true)

type authPermissionDataDS struct {
	Full        types.String `tfsdk:"full"`
	Instances   types.Set    `tfsdk:"instances"`
	Operations  types.Set    `tfsdk:"operations"`
	TypeEscaped types.String `tfsdk:"type_escaped"`
}

var authStoredAccountAttributeAttrTypesDS = objectAttrsTypeDSAuthStoredAccountAttribute(false)
var authStoredAccountAttributeAttrTypesDSRecurse = objectAttrsTypeDSAuthStoredAccountAttribute(true)

type authStoredAccountAttributeDataDS struct {
	Name  types.String `tfsdk:"name"`
	Value types.String `tfsdk:"value"`
}

var authStoredAccountAttributesAttrTypesDS = objectAttrsTypeDSAuthStoredAccountAttributes(false)
var authStoredAccountAttributesAttrTypesDSRecurse = objectAttrsTypeDSAuthStoredAccountAttributes(true)

type authStoredAccountAttributesDataDS struct {
	Attributes types.Set `tfsdk:"attributes"`
}

var certificateCertificateAttrTypesDS = objectAttrsTypeDSCertificateCertificate(false)
var certificateCertificateAttrTypesDSRecurse = objectAttrsTypeDSCertificateCertificate(true)

type certificateCertificateDataDS struct {
	Links                            types.Set    `tfsdk:"links"`
	Permissions                      types.Set    `tfsdk:"permissions"`
	Alias                            types.String `tfsdk:"alias"`
	CertificateCertificatePrimerType types.String `tfsdk:"type"`
	CertificateData                  types.String `tfsdk:"certificate_data"`
	Expiration                       types.String `tfsdk:"expiration"`
	FingerprintSha1                  types.String `tfsdk:"fingerprint_sha1"`
	FingerprintSha256                types.String `tfsdk:"fingerprint_sha256"`
	Global                           types.Bool   `tfsdk:"global"`
	SubjectDN                        types.String `tfsdk:"subject_dn"`
	UUID                             types.String `tfsdk:"uuid"`
	Additional                       types.List   `tfsdk:"additional"`
	Audit                            types.Object `tfsdk:"audit" tkhao:"audit"`
	KeyData                          types.String `tfsdk:"key_data"`
}

var certificateCertificatePrimerAttrTypesDS = objectAttrsTypeDSCertificateCertificatePrimer(false)
var certificateCertificatePrimerAttrTypesDSRecurse = objectAttrsTypeDSCertificateCertificatePrimer(true)

type certificateCertificatePrimerDataDS struct {
	Links                            types.Set    `tfsdk:"links"`
	Permissions                      types.Set    `tfsdk:"permissions"`
	Alias                            types.String `tfsdk:"alias"`
	CertificateCertificatePrimerType types.String `tfsdk:"type"`
	CertificateData                  types.String `tfsdk:"certificate_data"`
	Expiration                       types.String `tfsdk:"expiration"`
	FingerprintSha1                  types.String `tfsdk:"fingerprint_sha1"`
	FingerprintSha256                types.String `tfsdk:"fingerprint_sha256"`
	Global                           types.Bool   `tfsdk:"global"`
	SubjectDN                        types.String `tfsdk:"subject_dn"`
	UUID                             types.String `tfsdk:"uuid"`
}

var certificateCertificate_additionalObjectsAttrTypesDS = objectAttrsTypeDSCertificateCertificate_additionalObjects(false)
var certificateCertificate_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSCertificateCertificate_additionalObjects(true)

type certificateCertificate_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
}

var clientClientApplicationAttrTypesDS = objectAttrsTypeDSClientClientApplication(false)
var clientClientApplicationAttrTypesDSRecurse = objectAttrsTypeDSClientClientApplication(true)

type clientClientApplicationDataDS struct {
	Links                             types.Set    `tfsdk:"links"`
	Permissions                       types.Set    `tfsdk:"permissions"`
	ClientClientApplicationPrimerType types.String `tfsdk:"type"`
	ClientID                          types.String `tfsdk:"client_id"`
	Name                              types.String `tfsdk:"name"`
	Scopes                            types.Set    `tfsdk:"scopes"`
	SsoApplication                    types.Bool   `tfsdk:"sso_application"`
	UUID                              types.String `tfsdk:"uuid"`
	Additional                        types.List   `tfsdk:"additional"`
	Audit                             types.Object `tfsdk:"audit" tkhao:"audit"`
	Groupclients                      types.List   `tfsdk:"groupclients" tkhao:"groupclients"`
	Groups                            types.List   `tfsdk:"groups" tkhao:"groups"`
	Secret                            types.Object `tfsdk:"secret" tkhao:"secret"`
	Tile                              types.Object `tfsdk:"tile" tkhao:"tile"`
	VaultRecordCount                  types.Int64  `tfsdk:"vault_record_count" tkhao:"vaultRecordCount"`
	LastModifiedAt                    types.String `tfsdk:"last_modified_at"`
	Owner                             types.Object `tfsdk:"owner"`
	TechnicalAdministrator            types.Object `tfsdk:"technical_administrator"`
	LDAPClient                        types.Object `tfsdk:"ldap_client"`
	OAuth2Client                      types.Object `tfsdk:"oauth2_client"`
	Saml2Client                       types.Object `tfsdk:"saml2_client"`
}

var clientClientApplicationLinkableWrapperAttrTypesDS = objectAttrsTypeDSClientClientApplicationLinkableWrapper(false)
var clientClientApplicationLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSClientClientApplicationLinkableWrapper(true)

type clientClientApplicationLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var clientClientApplicationPrimerAttrTypesDS = objectAttrsTypeDSClientClientApplicationPrimer(false)
var clientClientApplicationPrimerAttrTypesDSRecurse = objectAttrsTypeDSClientClientApplicationPrimer(true)

type clientClientApplicationPrimerDataDS struct {
	Links                             types.Set    `tfsdk:"links"`
	Permissions                       types.Set    `tfsdk:"permissions"`
	ClientClientApplicationPrimerType types.String `tfsdk:"type"`
	ClientID                          types.String `tfsdk:"client_id"`
	Name                              types.String `tfsdk:"name"`
	Scopes                            types.Set    `tfsdk:"scopes"`
	SsoApplication                    types.Bool   `tfsdk:"sso_application"`
	UUID                              types.String `tfsdk:"uuid"`
}

var clientClientApplication_additionalObjectsAttrTypesDS = objectAttrsTypeDSClientClientApplication_additionalObjects(false)
var clientClientApplication_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSClientClientApplication_additionalObjects(true)

type clientClientApplication_additionalObjectsDataDS struct {
	Audit            types.Object `tfsdk:"audit"`
	Groupclients     types.List   `tfsdk:"groupclients"`
	Groups           types.List   `tfsdk:"groups"`
	Secret           types.Object `tfsdk:"secret"`
	Tile             types.Object `tfsdk:"tile"`
	VaultRecordCount types.Int64  `tfsdk:"vault_record_count"`
}

var clientLdapClientAttrTypesDS = objectAttrsTypeDSClientLdapClient(false)
var clientLdapClientAttrTypesDSRecurse = objectAttrsTypeDSClientLdapClient(true)

type clientLdapClientDataDS struct {
	BindDN              types.String `tfsdk:"bind_dn"`
	ClientCertificate   types.Object `tfsdk:"client_certificate"`
	ShareSecretInVault  types.Bool   `tfsdk:"share_secret_in_vault"`
	SharedSecret        types.Object `tfsdk:"shared_secret"`
	UsedForProvisioning types.Bool   `tfsdk:"used_for_provisioning"`
}

var clientOAuth2ClientAttrTypesDS = objectAttrsTypeDSClientOAuth2Client(false)
var clientOAuth2ClientAttrTypesDSRecurse = objectAttrsTypeDSClientOAuth2Client(true)

type clientOAuth2ClientDataDS struct {
	AccountPermissions   types.Set    `tfsdk:"account_permissions"`
	Attributes           types.Map    `tfsdk:"attributes"`
	CallbackURI          types.String `tfsdk:"callback_uri"`
	DebugMode            types.Bool   `tfsdk:"debug_mode"`
	IDTokenClaims        types.String `tfsdk:"id_token_claims"`
	InitiateLoginURI     types.String `tfsdk:"initiate_login_uri"`
	Profile              types.String `tfsdk:"profile"`
	ResourceURIs         types.String `tfsdk:"resource_uris"`
	ShareSecretInVault   types.Bool   `tfsdk:"share_secret_in_vault"`
	SharedSecret         types.Object `tfsdk:"shared_secret"`
	ShowLandingPage      types.Bool   `tfsdk:"show_landing_page"`
	UseClientCredentials types.Bool   `tfsdk:"use_client_credentials"`
}

var clientOAuth2ClientPermissionAttrTypesDS = objectAttrsTypeDSClientOAuth2ClientPermission(false)
var clientOAuth2ClientPermissionAttrTypesDSRecurse = objectAttrsTypeDSClientOAuth2ClientPermission(true)

type clientOAuth2ClientPermissionDataDS struct {
	Links       types.Set    `tfsdk:"links"`
	Permissions types.Set    `tfsdk:"permissions"`
	Additional  types.List   `tfsdk:"additional"`
	Audit       types.Object `tfsdk:"audit" tkhao:"audit"`
	ForGroup    types.Object `tfsdk:"for_group"`
	ForSystem   types.Object `tfsdk:"for_system"`
	Value       types.String `tfsdk:"value"`
}

var clientOAuth2ClientPermissionWithClientAttrTypesDS = objectAttrsTypeDSClientOAuth2ClientPermissionWithClient(false)
var clientOAuth2ClientPermissionWithClientAttrTypesDSRecurse = objectAttrsTypeDSClientOAuth2ClientPermissionWithClient(true)

type clientOAuth2ClientPermissionWithClientDataDS struct {
	Links       types.Set    `tfsdk:"links"`
	Permissions types.Set    `tfsdk:"permissions"`
	Additional  types.List   `tfsdk:"additional"`
	Audit       types.Object `tfsdk:"audit" tkhao:"audit"`
	ForGroup    types.Object `tfsdk:"for_group"`
	ForSystem   types.Object `tfsdk:"for_system"`
	Value       types.String `tfsdk:"value"`
	Client      types.Object `tfsdk:"client"`
}

var clientOAuth2ClientPermissionWithClientLinkableWrapperAttrTypesDS = objectAttrsTypeDSClientOAuth2ClientPermissionWithClientLinkableWrapper(false)
var clientOAuth2ClientPermissionWithClientLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSClientOAuth2ClientPermissionWithClientLinkableWrapper(true)

type clientOAuth2ClientPermissionWithClientLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var clientOAuth2ClientPermission_additionalObjectsAttrTypesDS = objectAttrsTypeDSClientOAuth2ClientPermission_additionalObjects(false)
var clientOAuth2ClientPermission_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSClientOAuth2ClientPermission_additionalObjects(true)

type clientOAuth2ClientPermission_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
}

var clientSaml2ClientAttrTypesDS = objectAttrsTypeDSClientSaml2Client(false)
var clientSaml2ClientAttrTypesDSRecurse = objectAttrsTypeDSClientSaml2Client(true)

type clientSaml2ClientDataDS struct {
	Attributes    types.Map    `tfsdk:"attributes"`
	Metadata      types.String `tfsdk:"metadata"`
	MetadataURL   types.String `tfsdk:"metadata_url"`
	SubjectFormat types.String `tfsdk:"subject_format"`
}

var directoryAccountDirectoryAttrTypesDS = objectAttrsTypeDSDirectoryAccountDirectory(false)
var directoryAccountDirectoryAttrTypesDSRecurse = objectAttrsTypeDSDirectoryAccountDirectory(true)

type directoryAccountDirectoryDataDS struct {
	Links                               types.Set    `tfsdk:"links"`
	Permissions                         types.Set    `tfsdk:"permissions"`
	AccountValiditySupported            types.Bool   `tfsdk:"account_validity_supported"`
	Active                              types.Bool   `tfsdk:"active"`
	DirectoryAccountDirectoryPrimerType types.String `tfsdk:"type"`
	Name                                types.String `tfsdk:"name"`
	UUID                                types.String `tfsdk:"uuid"`
	Additional                          types.List   `tfsdk:"additional"`
	Audit                               types.Object `tfsdk:"audit" tkhao:"audit"`
	Markers                             types.Object `tfsdk:"markers" tkhao:"markers"`
	Status                              types.Object `tfsdk:"status" tkhao:"status"`
	BaseOrganizationalUnit              types.Object `tfsdk:"base_organizational_unit"`
	DefaultDirectory                    types.Bool   `tfsdk:"default_directory"`
	HelpdeskGroup                       types.Object `tfsdk:"helpdesk_group"`
	Restrict2fa                         types.Bool   `tfsdk:"restrict2fa"`
	RotatingPassword                    types.String `tfsdk:"rotating_password"`
	UsernameCustomizable                types.Bool   `tfsdk:"username_customizable"`
	InternalDirectory                   types.Object `tfsdk:"internal_directory"`
	LDAPDirectory                       types.Object `tfsdk:"ldap_directory"`
	MaintenanceDirectory                types.Object `tfsdk:"maintenance_directory"`
	OIDCDirectory                       types.Object `tfsdk:"oidc_directory"`
}

var directoryAccountDirectoryLinkableWrapperAttrTypesDS = objectAttrsTypeDSDirectoryAccountDirectoryLinkableWrapper(false)
var directoryAccountDirectoryLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSDirectoryAccountDirectoryLinkableWrapper(true)

type directoryAccountDirectoryLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var directoryAccountDirectoryPrimerAttrTypesDS = objectAttrsTypeDSDirectoryAccountDirectoryPrimer(false)
var directoryAccountDirectoryPrimerAttrTypesDSRecurse = objectAttrsTypeDSDirectoryAccountDirectoryPrimer(true)

type directoryAccountDirectoryPrimerDataDS struct {
	Links                               types.Set    `tfsdk:"links"`
	Permissions                         types.Set    `tfsdk:"permissions"`
	AccountValiditySupported            types.Bool   `tfsdk:"account_validity_supported"`
	Active                              types.Bool   `tfsdk:"active"`
	DirectoryAccountDirectoryPrimerType types.String `tfsdk:"type"`
	Name                                types.String `tfsdk:"name"`
	UUID                                types.String `tfsdk:"uuid"`
}

var directoryAccountDirectoryStatusReportAttrTypesDS = objectAttrsTypeDSDirectoryAccountDirectoryStatusReport(false)
var directoryAccountDirectoryStatusReportAttrTypesDSRecurse = objectAttrsTypeDSDirectoryAccountDirectoryStatusReport(true)

type directoryAccountDirectoryStatusReportDataDS struct {
	Accounts types.Int64  `tfsdk:"accounts"`
	Reason   types.String `tfsdk:"reason"`
	Status   types.String `tfsdk:"status"`
}

var directoryAccountDirectorySummaryAttrTypesDS = objectAttrsTypeDSDirectoryAccountDirectorySummary(false)
var directoryAccountDirectorySummaryAttrTypesDSRecurse = objectAttrsTypeDSDirectoryAccountDirectorySummary(true)

type directoryAccountDirectorySummaryDataDS struct {
	Links                                types.Set    `tfsdk:"links"`
	Permissions                          types.Set    `tfsdk:"permissions"`
	DirectoryAccountDirectorySummaryType types.String `tfsdk:"type"`
	DomainRestriction                    types.String `tfsdk:"domain_restriction"`
	FullyResolvedIssuer                  types.String `tfsdk:"fully_resolved_issuer"`
	Name                                 types.String `tfsdk:"name"`
	Status                               types.Object `tfsdk:"status"`
	UsernameCustomizable                 types.Bool   `tfsdk:"username_customizable"`
}

var directoryAccountDirectorySummaryLinkableWrapperAttrTypesDS = objectAttrsTypeDSDirectoryAccountDirectorySummaryLinkableWrapper(false)
var directoryAccountDirectorySummaryLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSDirectoryAccountDirectorySummaryLinkableWrapper(true)

type directoryAccountDirectorySummaryLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var directoryAccountDirectory_additionalObjectsAttrTypesDS = objectAttrsTypeDSDirectoryAccountDirectory_additionalObjects(false)
var directoryAccountDirectory_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSDirectoryAccountDirectory_additionalObjects(true)

type directoryAccountDirectory_additionalObjectsDataDS struct {
	Audit   types.Object `tfsdk:"audit"`
	Markers types.Object `tfsdk:"markers"`
	Status  types.Object `tfsdk:"status"`
}

var directoryInternalDirectoryAttrTypesDS = objectAttrsTypeDSDirectoryInternalDirectory(false)
var directoryInternalDirectoryAttrTypesDSRecurse = objectAttrsTypeDSDirectoryInternalDirectory(true)

type directoryInternalDirectoryDataDS struct {
	Owner types.Object `tfsdk:"owner"`
}

var directoryLDAPDirectoryAttrTypesDS = objectAttrsTypeDSDirectoryLDAPDirectory(false)
var directoryLDAPDirectoryAttrTypesDSRecurse = objectAttrsTypeDSDirectoryLDAPDirectory(true)

type directoryLDAPDirectoryDataDS struct {
	AttributesToStore          types.String `tfsdk:"attributes_to_store"`
	BaseDN                     types.String `tfsdk:"base_dn"`
	ClientCertificate          types.Object `tfsdk:"client_certificate"`
	Dialect                    types.String `tfsdk:"dialect"`
	FailoverHost               types.String `tfsdk:"failover_host"`
	FailoverTrustedCertificate types.Object `tfsdk:"failover_trusted_certificate"`
	Host                       types.String `tfsdk:"host"`
	PasswordRecovery           types.String `tfsdk:"password_recovery"`
	Port                       types.Int64  `tfsdk:"port"`
	SearchBindDN               types.String `tfsdk:"search_bind_dn"`
	SearchBindPassword         types.String `tfsdk:"search_bind_password"`
	SearchFilter               types.String `tfsdk:"search_filter"`
	TLS                        types.String `tfsdk:"tls"`
	TrustedCertificate         types.Object `tfsdk:"trusted_certificate"`
}

var directoryMaintenanceDirectoryAttrTypesDS = objectAttrsTypeDSDirectoryMaintenanceDirectory(false)
var directoryMaintenanceDirectoryAttrTypesDSRecurse = objectAttrsTypeDSDirectoryMaintenanceDirectory(true)

type directoryMaintenanceDirectoryDataDS struct {
}

var directoryOIDCDirectoryAttrTypesDS = objectAttrsTypeDSDirectoryOIDCDirectory(false)
var directoryOIDCDirectoryAttrTypesDSRecurse = objectAttrsTypeDSDirectoryOIDCDirectory(true)

type directoryOIDCDirectoryDataDS struct {
	AcrValues           types.String `tfsdk:"acr_values"`
	AttributesToStore   types.String `tfsdk:"attributes_to_store"`
	ClientID            types.String `tfsdk:"client_id"`
	ClientSecret        types.String `tfsdk:"client_secret"`
	DomainRestriction   types.String `tfsdk:"domain_restriction"`
	Enforces2fa         types.Bool   `tfsdk:"enforces2fa"`
	FullyResolvedIssuer types.String `tfsdk:"fully_resolved_issuer"`
	Issuer              types.String `tfsdk:"issuer"`
	LogoutURL           types.String `tfsdk:"logout_url"`
	SendLoginHint       types.Bool   `tfsdk:"send_login_hint"`
	VendorEscaped       types.String `tfsdk:"vendor_escaped"`
}

var groupAccountGroupAttrTypesDS = objectAttrsTypeDSGroupAccountGroup(false)
var groupAccountGroupAttrTypesDSRecurse = objectAttrsTypeDSGroupAccountGroup(true)

type groupAccountGroupDataDS struct {
	Links                  types.Set    `tfsdk:"links"`
	Permissions            types.Set    `tfsdk:"permissions"`
	Admin                  types.Bool   `tfsdk:"admin"`
	Name                   types.String `tfsdk:"name"`
	OrganizationalUnit     types.Object `tfsdk:"organizational_unit"`
	UUID                   types.String `tfsdk:"uuid"`
	Additional             types.List   `tfsdk:"additional"`
	Audit                  types.Object `tfsdk:"audit" tkhao:"audit"`
	Vault                  types.Object `tfsdk:"vault" tkhao:"vault"`
	EndDate                types.String `tfsdk:"end_date"`
	Folder                 types.Object `tfsdk:"folder"`
	LastUsed               types.String `tfsdk:"last_used"`
	ProvisioningEndTime    types.String `tfsdk:"provisioning_end_time"`
	Rights                 types.String `tfsdk:"rights"`
	VisibleForProvisioning types.Bool   `tfsdk:"visible_for_provisioning"`
}

var groupAccountGroupLinkableWrapperAttrTypesDS = objectAttrsTypeDSGroupAccountGroupLinkableWrapper(false)
var groupAccountGroupLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSGroupAccountGroupLinkableWrapper(true)

type groupAccountGroupLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var groupAccountGroup_additionalObjectsAttrTypesDS = objectAttrsTypeDSGroupAccountGroup_additionalObjects(false)
var groupAccountGroup_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSGroupAccountGroup_additionalObjects(true)

type groupAccountGroup_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
	Vault types.Object `tfsdk:"vault"`
}

var groupAuthorizedGroupsWrapperAttrTypesDS = objectAttrsTypeDSGroupAuthorizedGroupsWrapper(false)
var groupAuthorizedGroupsWrapperAttrTypesDSRecurse = objectAttrsTypeDSGroupAuthorizedGroupsWrapper(true)

type groupAuthorizedGroupsWrapperDataDS struct {
	Items      types.Set   `tfsdk:"items"`
	GroupCount types.Int64 `tfsdk:"group_count"`
}

var groupGroupAttrTypesDS = objectAttrsTypeDSGroupGroup(false)
var groupGroupAttrTypesDSRecurse = objectAttrsTypeDSGroupGroup(true)

type groupGroupDataDS struct {
	Links                        types.Set    `tfsdk:"links"`
	Permissions                  types.Set    `tfsdk:"permissions"`
	Admin                        types.Bool   `tfsdk:"admin"`
	Name                         types.String `tfsdk:"name"`
	OrganizationalUnit           types.Object `tfsdk:"organizational_unit"`
	UUID                         types.String `tfsdk:"uuid"`
	Additional                   types.List   `tfsdk:"additional"`
	Accounts                     types.List   `tfsdk:"accounts" tkhao:"accounts"`
	AdministeredClients          types.List   `tfsdk:"administered_clients" tkhao:"administeredClients"`
	AdministeredSystems          types.List   `tfsdk:"administered_systems" tkhao:"administeredSystems"`
	Admins                       types.List   `tfsdk:"admins" tkhao:"admins"`
	Audit                        types.Object `tfsdk:"audit" tkhao:"audit"`
	AuthorizedGroups             types.Object `tfsdk:"authorized_groups" tkhao:"authorizedGroups"`
	ClientPermissions            types.List   `tfsdk:"client_permissions" tkhao:"clientPermissions"`
	Clients                      types.List   `tfsdk:"clients" tkhao:"clients"`
	ContentAdministeredSystems   types.List   `tfsdk:"content_administered_systems" tkhao:"contentAdministeredSystems"`
	Groupauditinginfo            types.Object `tfsdk:"groupauditinginfo" tkhao:"groupauditinginfo"`
	Groupinfo                    types.Object `tfsdk:"groupinfo" tkhao:"groupinfo"`
	Helpdesk                     types.List   `tfsdk:"helpdesk" tkhao:"helpdesk"`
	Markers                      types.Object `tfsdk:"markers" tkhao:"markers"`
	Myaccount                    types.Object `tfsdk:"myaccount" tkhao:"myaccount"`
	Mydelegatedaccount           types.Object `tfsdk:"mydelegatedaccount" tkhao:"mydelegatedaccount"`
	NestedGroups                 types.List   `tfsdk:"nested_groups" tkhao:"nestedGroups"`
	OwnedClients                 types.List   `tfsdk:"owned_clients" tkhao:"ownedClients"`
	OwnedDirectories             types.List   `tfsdk:"owned_directories" tkhao:"ownedDirectories"`
	OwnedGroupsOnSystem          types.Object `tfsdk:"owned_groups_on_system" tkhao:"ownedGroupsOnSystem"`
	OwnedOrganizationalUnits     types.List   `tfsdk:"owned_organizational_units" tkhao:"ownedOrganizationalUnits"`
	OwnedSystems                 types.List   `tfsdk:"owned_systems" tkhao:"ownedSystems"`
	RecentAudits                 types.List   `tfsdk:"recent_audits" tkhao:"recentAudits"`
	Requeststatus                types.String `tfsdk:"requeststatus" tkhao:"requeststatus"`
	ServiceAccounts              types.List   `tfsdk:"service_accounts" tkhao:"serviceAccounts"`
	Systems                      types.List   `tfsdk:"systems" tkhao:"systems"`
	Vault                        types.Object `tfsdk:"vault" tkhao:"vault"`
	Webhooks                     types.List   `tfsdk:"webhooks" tkhao:"webhooks"`
	ApplicationAdministration    types.Bool   `tfsdk:"application_administration"`
	AuditConfig                  types.Object `tfsdk:"audit_config"`
	AuditRequested               types.Bool   `tfsdk:"audit_requested"`
	Auditor                      types.Bool   `tfsdk:"auditor"`
	AuthorizingGroupAuditing     types.Object `tfsdk:"authorizing_group_auditing"`
	AuthorizingGroupDelegation   types.Object `tfsdk:"authorizing_group_delegation"`
	AuthorizingGroupMembership   types.Object `tfsdk:"authorizing_group_membership"`
	AuthorizingGroupProvisioning types.Object `tfsdk:"authorizing_group_provisioning"`
	AuthorizingGroupTypes        types.Set    `tfsdk:"authorizing_group_types"`
	Classification               types.Object `tfsdk:"classification"`
	Description                  types.String `tfsdk:"description"`
	ExtendedAccess               types.String `tfsdk:"extended_access"`
	HideAuditTrail               types.Bool   `tfsdk:"hide_audit_trail"`
	NestedUnder                  types.Object `tfsdk:"nested_under"`
	PrivateGroup                 types.Bool   `tfsdk:"private_group"`
	RecordTrail                  types.Bool   `tfsdk:"record_trail"`
	RotatingPasswordRequired     types.Bool   `tfsdk:"rotating_password_required"`
	SingleManaged                types.Bool   `tfsdk:"single_managed"`
	VaultRecovery                types.String `tfsdk:"vault_recovery"`
	VaultRequiresActivation      types.Bool   `tfsdk:"vault_requires_activation"`
}

var groupGroupAccountAttrTypesDS = objectAttrsTypeDSGroupGroupAccount(false)
var groupGroupAccountAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupAccount(true)

type groupGroupAccountDataDS struct {
	Links                  types.Set    `tfsdk:"links"`
	Permissions            types.Set    `tfsdk:"permissions"`
	DisplayName            types.String `tfsdk:"display_name"`
	LastActive             types.String `tfsdk:"last_active"`
	Username               types.String `tfsdk:"username"`
	UUID                   types.String `tfsdk:"uuid"`
	Validity               types.String `tfsdk:"validity"`
	Additional             types.List   `tfsdk:"additional"`
	Audit                  types.Object `tfsdk:"audit" tkhao:"audit"`
	Directory              types.Object `tfsdk:"directory"`
	DisconnectedNested     types.Bool   `tfsdk:"disconnected_nested"`
	EndDate                types.String `tfsdk:"end_date"`
	LastUsed               types.String `tfsdk:"last_used"`
	Nested                 types.Bool   `tfsdk:"nested"`
	ProvisioningEndTime    types.String `tfsdk:"provisioning_end_time"`
	Rights                 types.String `tfsdk:"rights"`
	TwoFactorStatus        types.String `tfsdk:"two_factor_status"`
	VisibleForProvisioning types.Bool   `tfsdk:"visible_for_provisioning"`
}

var groupGroupAccountLinkableWrapperAttrTypesDS = objectAttrsTypeDSGroupGroupAccountLinkableWrapper(false)
var groupGroupAccountLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupAccountLinkableWrapper(true)

type groupGroupAccountLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var groupGroupAccount_additionalObjectsAttrTypesDS = objectAttrsTypeDSGroupGroupAccount_additionalObjects(false)
var groupGroupAccount_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupAccount_additionalObjects(true)

type groupGroupAccount_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
}

var groupGroupAuditConfigAttrTypesDS = objectAttrsTypeDSGroupGroupAuditConfig(false)
var groupGroupAuditConfigAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupAuditConfig(true)

type groupGroupAuditConfigDataDS struct {
	Links       types.Set `tfsdk:"links"`
	Permissions types.Set `tfsdk:"permissions"`
	Months      types.Set `tfsdk:"months"`
}

var groupGroupAuditingInfoAttrTypesDS = objectAttrsTypeDSGroupGroupAuditingInfo(false)
var groupGroupAuditingInfoAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupAuditingInfo(true)

type groupGroupAuditingInfoDataDS struct {
	AuditDueDate              types.String `tfsdk:"audit_due_date"`
	LastAuditDate             types.String `tfsdk:"last_audit_date"`
	NrAccounts                types.Int64  `tfsdk:"nr_accounts"`
	NrDisabledAccounts        types.Int64  `tfsdk:"nr_disabled_accounts"`
	NrDisabledManagers        types.Int64  `tfsdk:"nr_disabled_managers"`
	NrExpiredVaultRecords     types.Int64  `tfsdk:"nr_expired_vault_records"`
	NrManagers                types.Int64  `tfsdk:"nr_managers"`
	NrVaultRecordsWithEndDate types.Int64  `tfsdk:"nr_vault_records_with_end_date"`
}

var groupGroupClassificationAttrTypesDS = objectAttrsTypeDSGroupGroupClassification(false)
var groupGroupClassificationAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupClassification(true)

type groupGroupClassificationDataDS struct {
	Links                                types.Set    `tfsdk:"links"`
	Permissions                          types.Set    `tfsdk:"permissions"`
	Name                                 types.String `tfsdk:"name"`
	UUID                                 types.String `tfsdk:"uuid"`
	Additional                           types.List   `tfsdk:"additional"`
	Audit                                types.Object `tfsdk:"audit" tkhao:"audit"`
	Info                                 types.Object `tfsdk:"info" tkhao:"info"`
	AuthorizingGroupAuditingRequired     types.Bool   `tfsdk:"authorizing_group_auditing_required"`
	AuthorizingGroupDelegationRequired   types.Bool   `tfsdk:"authorizing_group_delegation_required"`
	AuthorizingGroupMembershipRequired   types.Bool   `tfsdk:"authorizing_group_membership_required"`
	AuthorizingGroupProvisioningRequired types.Bool   `tfsdk:"authorizing_group_provisioning_required"`
	DefaultClassification                types.Bool   `tfsdk:"default_classification"`
	Description                          types.String `tfsdk:"description"`
	MaximumAuditInterval                 types.Int64  `tfsdk:"maximum_audit_interval"`
	MinimumNrManagers                    types.Int64  `tfsdk:"minimum_nr_managers"`
	RecordTrailRequired                  types.Bool   `tfsdk:"record_trail_required"`
	RequiredMonths                       types.Set    `tfsdk:"required_months"`
	RotatingPasswordRequired             types.Bool   `tfsdk:"rotating_password_required"`
	VaultRequiresActivation              types.Bool   `tfsdk:"vault_requires_activation"`
}

var groupGroupClassificationInfoAttrTypesDS = objectAttrsTypeDSGroupGroupClassificationInfo(false)
var groupGroupClassificationInfoAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupClassificationInfo(true)

type groupGroupClassificationInfoDataDS struct {
	NrGroups types.Int64 `tfsdk:"nr_groups"`
}

var groupGroupClassificationPrimerAttrTypesDS = objectAttrsTypeDSGroupGroupClassificationPrimer(false)
var groupGroupClassificationPrimerAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupClassificationPrimer(true)

type groupGroupClassificationPrimerDataDS struct {
	Links       types.Set    `tfsdk:"links"`
	Permissions types.Set    `tfsdk:"permissions"`
	Name        types.String `tfsdk:"name"`
	UUID        types.String `tfsdk:"uuid"`
}

var groupGroupClassification_additionalObjectsAttrTypesDS = objectAttrsTypeDSGroupGroupClassification_additionalObjects(false)
var groupGroupClassification_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupClassification_additionalObjects(true)

type groupGroupClassification_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
	Info  types.Object `tfsdk:"info"`
}

var groupGroupClientAttrTypesDS = objectAttrsTypeDSGroupGroupClient(false)
var groupGroupClientAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupClient(true)

type groupGroupClientDataDS struct {
	Links                  types.Set    `tfsdk:"links"`
	Permissions            types.Set    `tfsdk:"permissions"`
	Additional             types.List   `tfsdk:"additional"`
	ActivationRequired     types.Bool   `tfsdk:"activation_required"`
	Audit                  types.Object `tfsdk:"audit" tkhao:"audit"`
	Client                 types.Object `tfsdk:"client"`
	Group                  types.Object `tfsdk:"group"`
	Owner                  types.Object `tfsdk:"owner"`
	TechnicalAdministrator types.Object `tfsdk:"technical_administrator"`
}

var groupGroupClientLinkableWrapperAttrTypesDS = objectAttrsTypeDSGroupGroupClientLinkableWrapper(false)
var groupGroupClientLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupClientLinkableWrapper(true)

type groupGroupClientLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var groupGroupClient_additionalObjectsAttrTypesDS = objectAttrsTypeDSGroupGroupClient_additionalObjects(false)
var groupGroupClient_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupClient_additionalObjects(true)

type groupGroupClient_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
}

var groupGroupFolderAttrTypesDS = objectAttrsTypeDSGroupGroupFolder(false)
var groupGroupFolderAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupFolder(true)

type groupGroupFolderDataDS struct {
	Links       types.Set    `tfsdk:"links"`
	Permissions types.Set    `tfsdk:"permissions"`
	Additional  types.List   `tfsdk:"additional"`
	Audit       types.Object `tfsdk:"audit" tkhao:"audit"`
	Name        types.String `tfsdk:"name"`
}

var groupGroupFolder_additionalObjectsAttrTypesDS = objectAttrsTypeDSGroupGroupFolder_additionalObjects(false)
var groupGroupFolder_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupFolder_additionalObjects(true)

type groupGroupFolder_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
}

var groupGroupInfoAttrTypesDS = objectAttrsTypeDSGroupGroupInfo(false)
var groupGroupInfoAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupInfo(true)

type groupGroupInfoDataDS struct {
	NrAccounts           types.Int64 `tfsdk:"nr_accounts"`
	NrAccountsWithVault  types.Int64 `tfsdk:"nr_accounts_with_vault"`
	NrAudits             types.Int64 `tfsdk:"nr_audits"`
	NrClients            types.Int64 `tfsdk:"nr_clients"`
	NrProvisionedSystems types.Int64 `tfsdk:"nr_provisioned_systems"`
	NrVaultRecords       types.Int64 `tfsdk:"nr_vault_records"`
}

var groupGroupLinkableWrapperAttrTypesDS = objectAttrsTypeDSGroupGroupLinkableWrapper(false)
var groupGroupLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupLinkableWrapper(true)

type groupGroupLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var groupGroupPrimerAttrTypesDS = objectAttrsTypeDSGroupGroupPrimer(false)
var groupGroupPrimerAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupPrimer(true)

type groupGroupPrimerDataDS struct {
	Links              types.Set    `tfsdk:"links"`
	Permissions        types.Set    `tfsdk:"permissions"`
	Admin              types.Bool   `tfsdk:"admin"`
	Name               types.String `tfsdk:"name"`
	OrganizationalUnit types.Object `tfsdk:"organizational_unit"`
	UUID               types.String `tfsdk:"uuid"`
}

var groupGroupPrimerLinkableWrapperAttrTypesDS = objectAttrsTypeDSGroupGroupPrimerLinkableWrapper(false)
var groupGroupPrimerLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSGroupGroupPrimerLinkableWrapper(true)

type groupGroupPrimerLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var groupGroup_additionalObjectsAttrTypesDS = objectAttrsTypeDSGroupGroup_additionalObjects(false)
var groupGroup_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSGroupGroup_additionalObjects(true)

type groupGroup_additionalObjectsDataDS struct {
	Accounts                   types.List   `tfsdk:"accounts"`
	AdministeredClients        types.List   `tfsdk:"administered_clients"`
	AdministeredSystems        types.List   `tfsdk:"administered_systems"`
	Admins                     types.List   `tfsdk:"admins"`
	Audit                      types.Object `tfsdk:"audit"`
	AuthorizedGroups           types.Object `tfsdk:"authorized_groups"`
	ClientPermissions          types.List   `tfsdk:"client_permissions"`
	Clients                    types.List   `tfsdk:"clients"`
	ContentAdministeredSystems types.List   `tfsdk:"content_administered_systems"`
	Groupauditinginfo          types.Object `tfsdk:"groupauditinginfo"`
	Groupinfo                  types.Object `tfsdk:"groupinfo"`
	Helpdesk                   types.List   `tfsdk:"helpdesk"`
	Markers                    types.Object `tfsdk:"markers"`
	Myaccount                  types.Object `tfsdk:"myaccount"`
	Mydelegatedaccount         types.Object `tfsdk:"mydelegatedaccount"`
	NestedGroups               types.List   `tfsdk:"nested_groups"`
	OwnedClients               types.List   `tfsdk:"owned_clients"`
	OwnedDirectories           types.List   `tfsdk:"owned_directories"`
	OwnedGroupsOnSystem        types.Object `tfsdk:"owned_groups_on_system"`
	OwnedOrganizationalUnits   types.List   `tfsdk:"owned_organizational_units"`
	OwnedSystems               types.List   `tfsdk:"owned_systems"`
	RecentAudits               types.List   `tfsdk:"recent_audits"`
	Requeststatus              types.String `tfsdk:"requeststatus"`
	ServiceAccounts            types.List   `tfsdk:"service_accounts"`
	Systems                    types.List   `tfsdk:"systems"`
	Vault                      types.Object `tfsdk:"vault"`
	Webhooks                   types.List   `tfsdk:"webhooks"`
}

var groupProvisioningGroupAttrTypesDS = objectAttrsTypeDSGroupProvisioningGroup(false)
var groupProvisioningGroupAttrTypesDSRecurse = objectAttrsTypeDSGroupProvisioningGroup(true)

type groupProvisioningGroupDataDS struct {
	Links              types.Set    `tfsdk:"links"`
	Permissions        types.Set    `tfsdk:"permissions"`
	Additional         types.List   `tfsdk:"additional"`
	ActivationRequired types.Bool   `tfsdk:"activation_required"`
	Audit              types.Object `tfsdk:"audit" tkhao:"audit"`
	Group              types.Object `tfsdk:"group"`
	GroupOnSystem      types.Object `tfsdk:"group_on_system"`
}

var groupProvisioningGroupLinkableWrapperAttrTypesDS = objectAttrsTypeDSGroupProvisioningGroupLinkableWrapper(false)
var groupProvisioningGroupLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSGroupProvisioningGroupLinkableWrapper(true)

type groupProvisioningGroupLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var groupProvisioningGroup_additionalObjectsAttrTypesDS = objectAttrsTypeDSGroupProvisioningGroup_additionalObjects(false)
var groupProvisioningGroup_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSGroupProvisioningGroup_additionalObjects(true)

type groupProvisioningGroup_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
}

var launchpadSsoApplicationLaunchpadTileAttrTypesDS = objectAttrsTypeDSLaunchpadSsoApplicationLaunchpadTile(false)
var launchpadSsoApplicationLaunchpadTileAttrTypesDSRecurse = objectAttrsTypeDSLaunchpadSsoApplicationLaunchpadTile(true)

type launchpadSsoApplicationLaunchpadTileDataDS struct {
	URI types.String `tfsdk:"uri"`
}

var launchpadVaultRecordLaunchpadTileAttrTypesDS = objectAttrsTypeDSLaunchpadVaultRecordLaunchpadTile(false)
var launchpadVaultRecordLaunchpadTileAttrTypesDSRecurse = objectAttrsTypeDSLaunchpadVaultRecordLaunchpadTile(true)

type launchpadVaultRecordLaunchpadTileDataDS struct {
}

var markItemMarkerAttrTypesDS = objectAttrsTypeDSMarkItemMarker(false)
var markItemMarkerAttrTypesDSRecurse = objectAttrsTypeDSMarkItemMarker(true)

type markItemMarkerDataDS struct {
	Level              types.String `tfsdk:"level"`
	MarkItemMarkerType types.String `tfsdk:"type"`
	Parameters         types.Map    `tfsdk:"parameters"`
}

var markItemMarkersAttrTypesDS = objectAttrsTypeDSMarkItemMarkers(false)
var markItemMarkersAttrTypesDSRecurse = objectAttrsTypeDSMarkItemMarkers(true)

type markItemMarkersDataDS struct {
	Markers types.Set `tfsdk:"markers"`
}

var organizationOrganizationalUnitAttrTypesDS = objectAttrsTypeDSOrganizationOrganizationalUnit(false)
var organizationOrganizationalUnitAttrTypesDSRecurse = objectAttrsTypeDSOrganizationOrganizationalUnit(true)

type organizationOrganizationalUnitDataDS struct {
	Links       types.Set    `tfsdk:"links"`
	Permissions types.Set    `tfsdk:"permissions"`
	Name        types.String `tfsdk:"name"`
	UUID        types.String `tfsdk:"uuid"`
	Additional  types.List   `tfsdk:"additional"`
	Audit       types.Object `tfsdk:"audit" tkhao:"audit"`
	Depth       types.Int64  `tfsdk:"depth"`
	Description types.String `tfsdk:"description"`
	Owner       types.Object `tfsdk:"owner"`
	Parent      types.Object `tfsdk:"parent"`
}

var organizationOrganizationalUnitLinkableWrapperAttrTypesDS = objectAttrsTypeDSOrganizationOrganizationalUnitLinkableWrapper(false)
var organizationOrganizationalUnitLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSOrganizationOrganizationalUnitLinkableWrapper(true)

type organizationOrganizationalUnitLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var organizationOrganizationalUnitPrimerAttrTypesDS = objectAttrsTypeDSOrganizationOrganizationalUnitPrimer(false)
var organizationOrganizationalUnitPrimerAttrTypesDSRecurse = objectAttrsTypeDSOrganizationOrganizationalUnitPrimer(true)

type organizationOrganizationalUnitPrimerDataDS struct {
	Links       types.Set    `tfsdk:"links"`
	Permissions types.Set    `tfsdk:"permissions"`
	Name        types.String `tfsdk:"name"`
	UUID        types.String `tfsdk:"uuid"`
}

var organizationOrganizationalUnit_additionalObjectsAttrTypesDS = objectAttrsTypeDSOrganizationOrganizationalUnit_additionalObjects(false)
var organizationOrganizationalUnit_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSOrganizationOrganizationalUnit_additionalObjects(true)

type organizationOrganizationalUnit_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
}

var provisioningAbstractProvisionedLDAPAttrTypesDS = objectAttrsTypeDSProvisioningAbstractProvisionedLDAP(false)
var provisioningAbstractProvisionedLDAPAttrTypesDSRecurse = objectAttrsTypeDSProvisioningAbstractProvisionedLDAP(true)

type provisioningAbstractProvisionedLDAPDataDS struct {
	Attributes                 types.Map    `tfsdk:"attributes"`
	BaseDN                     types.String `tfsdk:"base_dn"`
	BindDN                     types.String `tfsdk:"bind_dn"`
	BindPassword               types.String `tfsdk:"bind_password"`
	ClientCertificate          types.Object `tfsdk:"client_certificate"`
	FailoverHost               types.String `tfsdk:"failover_host"`
	FailoverTrustedCertificate types.Object `tfsdk:"failover_trusted_certificate"`
	GroupDN                    types.String `tfsdk:"group_dn"`
	Host                       types.String `tfsdk:"host"`
	ObjectClasses              types.String `tfsdk:"object_classes"`
	Port                       types.Int64  `tfsdk:"port"`
	ServiceAccountDN           types.String `tfsdk:"service_account_dn"`
	SshPublicKeySupported      types.Bool   `tfsdk:"ssh_public_key_supported"`
	TLS                        types.String `tfsdk:"tls"`
	TrustedCertificate         types.Object `tfsdk:"trusted_certificate"`
	UserDN                     types.String `tfsdk:"user_dn"`
}

var provisioningCircuitBreakerStatisticsAttrTypesDS = objectAttrsTypeDSProvisioningCircuitBreakerStatistics(false)
var provisioningCircuitBreakerStatisticsAttrTypesDSRecurse = objectAttrsTypeDSProvisioningCircuitBreakerStatistics(true)

type provisioningCircuitBreakerStatisticsDataDS struct {
	NumberOfFailedCalls       types.Int64  `tfsdk:"number_of_failed_calls"`
	NumberOfNotPermittedCalls types.Int64  `tfsdk:"number_of_not_permitted_calls"`
	NumberOfSuccessfulCalls   types.Int64  `tfsdk:"number_of_successful_calls"`
	State                     types.String `tfsdk:"state"`
}

var provisioningGroupOnSystemAttrTypesDS = objectAttrsTypeDSProvisioningGroupOnSystem(false)
var provisioningGroupOnSystemAttrTypesDSRecurse = objectAttrsTypeDSProvisioningGroupOnSystem(true)

type provisioningGroupOnSystemDataDS struct {
	Links                               types.Set    `tfsdk:"links"`
	Permissions                         types.Set    `tfsdk:"permissions"`
	DisplayName                         types.String `tfsdk:"display_name"`
	NameInSystem                        types.String `tfsdk:"name_in_system"`
	ProvisioningGroupOnSystemPrimerType types.String `tfsdk:"type"`
	ShortNameInSystem                   types.String `tfsdk:"short_name_in_system"`
	Additional                          types.List   `tfsdk:"additional"`
	Audit                               types.Object `tfsdk:"audit" tkhao:"audit"`
	Provgroups                          types.List   `tfsdk:"provgroups" tkhao:"provgroups"`
	ServiceAccounts                     types.List   `tfsdk:"service_accounts" tkhao:"serviceAccounts"`
	Owner                               types.Object `tfsdk:"owner"`
}

var provisioningGroupOnSystemLinkableWrapperAttrTypesDS = objectAttrsTypeDSProvisioningGroupOnSystemLinkableWrapper(false)
var provisioningGroupOnSystemLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSProvisioningGroupOnSystemLinkableWrapper(true)

type provisioningGroupOnSystemLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var provisioningGroupOnSystemPrimerAttrTypesDS = objectAttrsTypeDSProvisioningGroupOnSystemPrimer(false)
var provisioningGroupOnSystemPrimerAttrTypesDSRecurse = objectAttrsTypeDSProvisioningGroupOnSystemPrimer(true)

type provisioningGroupOnSystemPrimerDataDS struct {
	Links                               types.Set    `tfsdk:"links"`
	Permissions                         types.Set    `tfsdk:"permissions"`
	DisplayName                         types.String `tfsdk:"display_name"`
	NameInSystem                        types.String `tfsdk:"name_in_system"`
	ProvisioningGroupOnSystemPrimerType types.String `tfsdk:"type"`
	ShortNameInSystem                   types.String `tfsdk:"short_name_in_system"`
}

var provisioningGroupOnSystemTypesAttrTypesDS = objectAttrsTypeDSProvisioningGroupOnSystemTypes(false)
var provisioningGroupOnSystemTypesAttrTypesDSRecurse = objectAttrsTypeDSProvisioningGroupOnSystemTypes(true)

type provisioningGroupOnSystemTypesDataDS struct {
	Types types.Set `tfsdk:"types"`
}

var provisioningGroupOnSystem_additionalObjectsAttrTypesDS = objectAttrsTypeDSProvisioningGroupOnSystem_additionalObjects(false)
var provisioningGroupOnSystem_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSProvisioningGroupOnSystem_additionalObjects(true)

type provisioningGroupOnSystem_additionalObjectsDataDS struct {
	Audit           types.Object `tfsdk:"audit"`
	Provgroups      types.List   `tfsdk:"provgroups"`
	ServiceAccounts types.List   `tfsdk:"service_accounts"`
}

var provisioningOwnedGroupOnSystemsWrapperAttrTypesDS = objectAttrsTypeDSProvisioningOwnedGroupOnSystemsWrapper(false)
var provisioningOwnedGroupOnSystemsWrapperAttrTypesDSRecurse = objectAttrsTypeDSProvisioningOwnedGroupOnSystemsWrapper(true)

type provisioningOwnedGroupOnSystemsWrapperDataDS struct {
	Items         types.Set   `tfsdk:"items"`
	UnlinkedCount types.Int64 `tfsdk:"unlinked_count"`
}

var provisioningProvisionNumberSequenceAttrTypesDS = objectAttrsTypeDSProvisioningProvisionNumberSequence(false)
var provisioningProvisionNumberSequenceAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionNumberSequence(true)

type provisioningProvisionNumberSequenceDataDS struct {
	Links        types.Set    `tfsdk:"links"`
	Permissions  types.Set    `tfsdk:"permissions"`
	Additional   types.List   `tfsdk:"additional"`
	AccountCount types.Int64  `tfsdk:"account_count"`
	Audit        types.Object `tfsdk:"audit" tkhao:"audit"`
	Systems      types.List   `tfsdk:"systems" tkhao:"systems"`
	Name         types.String `tfsdk:"name"`
	NextUID      types.Int64  `tfsdk:"next_uid"`
}

var provisioningProvisionNumberSequence_additionalObjectsAttrTypesDS = objectAttrsTypeDSProvisioningProvisionNumberSequence_additionalObjects(false)
var provisioningProvisionNumberSequence_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionNumberSequence_additionalObjects(true)

type provisioningProvisionNumberSequence_additionalObjectsDataDS struct {
	Audit   types.Object `tfsdk:"audit"`
	Systems types.List   `tfsdk:"systems"`
}

var provisioningProvisionedADAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedAD(false)
var provisioningProvisionedADAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedAD(true)

type provisioningProvisionedADDataDS struct {
	SamAccountNameScheme types.String `tfsdk:"sam_account_name_scheme"`
}

var provisioningProvisionedAccountAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedAccount(false)
var provisioningProvisionedAccountAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedAccount(true)

type provisioningProvisionedAccountDataDS struct {
	Links       types.Set    `tfsdk:"links"`
	Permissions types.Set    `tfsdk:"permissions"`
	DisplayName types.String `tfsdk:"display_name"`
	LastActive  types.String `tfsdk:"last_active"`
	Username    types.String `tfsdk:"username"`
	UUID        types.String `tfsdk:"uuid"`
	Validity    types.String `tfsdk:"validity"`
	Additional  types.List   `tfsdk:"additional"`
	Audit       types.Object `tfsdk:"audit" tkhao:"audit"`
	UID         types.Int64  `tfsdk:"uid"`
}

var provisioningProvisionedAccount_additionalObjectsAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedAccount_additionalObjects(false)
var provisioningProvisionedAccount_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedAccount_additionalObjects(true)

type provisioningProvisionedAccount_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
}

var provisioningProvisionedAzureOIDCDirectoryAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedAzureOIDCDirectory(false)
var provisioningProvisionedAzureOIDCDirectoryAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedAzureOIDCDirectory(true)

type provisioningProvisionedAzureOIDCDirectoryDataDS struct {
	Directory types.Object `tfsdk:"directory"`
	Tenant    types.String `tfsdk:"tenant"`
}

var provisioningProvisionedAzureSyncLDAPDirectoryAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedAzureSyncLDAPDirectory(false)
var provisioningProvisionedAzureSyncLDAPDirectoryAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedAzureSyncLDAPDirectory(true)

type provisioningProvisionedAzureSyncLDAPDirectoryDataDS struct {
	ClientID     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Directory    types.Object `tfsdk:"directory"`
	Tenant       types.String `tfsdk:"tenant"`
}

var provisioningProvisionedAzureTenantAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedAzureTenant(false)
var provisioningProvisionedAzureTenantAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedAzureTenant(true)

type provisioningProvisionedAzureTenantDataDS struct {
	ClientID     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	IDpDomain    types.String `tfsdk:"idp_domain"`
	Tenant       types.String `tfsdk:"tenant"`
}

var provisioningProvisionedInternalLDAPAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedInternalLDAP(false)
var provisioningProvisionedInternalLDAPAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedInternalLDAP(true)

type provisioningProvisionedInternalLDAPDataDS struct {
	Client types.Object `tfsdk:"client"`
}

var provisioningProvisionedLDAPAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedLDAP(false)
var provisioningProvisionedLDAPAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedLDAP(true)

type provisioningProvisionedLDAPDataDS struct {
	Gid           types.Int64  `tfsdk:"gid"`
	HashingScheme types.String `tfsdk:"hashing_scheme"`
	Numbering     types.Object `tfsdk:"numbering"`
}

var provisioningProvisionedLDAPDirectoryAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedLDAPDirectory(false)
var provisioningProvisionedLDAPDirectoryAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedLDAPDirectory(true)

type provisioningProvisionedLDAPDirectoryDataDS struct {
	Directory types.Object `tfsdk:"directory"`
	GroupDN   types.String `tfsdk:"group_dn"`
}

var provisioningProvisionedNamespaceAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedNamespace(false)
var provisioningProvisionedNamespaceAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedNamespace(true)

type provisioningProvisionedNamespaceDataDS struct {
	BaseSystem       types.Object `tfsdk:"base_system"`
	GroupDN          types.String `tfsdk:"group_dn"`
	ServiceAccountDN types.String `tfsdk:"service_account_dn"`
}

var provisioningProvisionedSCIMAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedSCIM(false)
var provisioningProvisionedSCIMAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedSCIM(true)

type provisioningProvisionedSCIMDataDS struct {
	AuthenticationScheme types.String `tfsdk:"authentication_scheme"`
	BasicAuthPassword    types.String `tfsdk:"basic_auth_password"`
	BasicAuthUsername    types.String `tfsdk:"basic_auth_username"`
	BearerToken          types.String `tfsdk:"bearer_token"`
	CustomHeaderName     types.String `tfsdk:"custom_header_name"`
	CustomHeaderValue    types.String `tfsdk:"custom_header_value"`
	URL                  types.String `tfsdk:"url"`
	VendorEscaped        types.String `tfsdk:"vendor_escaped"`
}

var provisioningProvisionedSystemAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedSystem(false)
var provisioningProvisionedSystemAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedSystem(true)

type provisioningProvisionedSystemDataDS struct {
	Links                                   types.Set    `tfsdk:"links"`
	Permissions                             types.Set    `tfsdk:"permissions"`
	Active                                  types.Bool   `tfsdk:"active"`
	Name                                    types.String `tfsdk:"name"`
	OrganizationalUnit                      types.Object `tfsdk:"organizational_unit"`
	ProvisioningProvisionedSystemPrimerType types.String `tfsdk:"type"`
	UUID                                    types.String `tfsdk:"uuid"`
	Additional                              types.List   `tfsdk:"additional"`
	AccountCount                            types.Int64  `tfsdk:"account_count"`
	Account                                 types.Object `tfsdk:"account" tkhao:"account"`
	Audit                                   types.Object `tfsdk:"audit" tkhao:"audit"`
	IssuedPermissions                       types.List   `tfsdk:"issued_permissions" tkhao:"issuedPermissions"`
	LoginName                               types.String `tfsdk:"login_name" tkhao:"loginName"`
	ManagementPermissions                   types.Object `tfsdk:"management_permissions" tkhao:"managementPermissions"`
	Markers                                 types.Object `tfsdk:"markers" tkhao:"markers"`
	Statistics                              types.Object `tfsdk:"statistics" tkhao:"statistics"`
	SupportedGroupTypes                     types.Object `tfsdk:"supported_group_types" tkhao:"supportedGroupTypes"`
	ContentAdministrator                    types.Object `tfsdk:"content_administrator"`
	ExternalUUID                            types.String `tfsdk:"external_uuid"`
	Owner                                   types.Object `tfsdk:"owner"`
	SelfServiceExistingGroups               types.Bool   `tfsdk:"self_service_existing_groups"`
	SelfServiceNewGroups                    types.Bool   `tfsdk:"self_service_new_groups"`
	SelfServiceNewNamespaces                types.Bool   `tfsdk:"self_service_new_namespaces"`
	SelfServiceServiceAccounts              types.Bool   `tfsdk:"self_service_service_accounts"`
	ShouldDestroyUnknownAccounts            types.Bool   `tfsdk:"should_destroy_unknown_accounts"`
	TechnicalAdministrator                  types.Object `tfsdk:"technical_administrator"`
	UsernamePrefix                          types.String `tfsdk:"username_prefix"`
	AbstractProvisionedLDAP                 types.Object `tfsdk:"abstract_provisioned_ldap"`
	ProvisionedAD                           types.Object `tfsdk:"provisioned_a_d"`
	ProvisionedAzureOIDCDirectory           types.Object `tfsdk:"provisioned_azure_oidc_directory"`
	ProvisionedAzureSyncLDAPDirectory       types.Object `tfsdk:"provisioned_azure_sync_ldap_directory"`
	ProvisionedAzureTenant                  types.Object `tfsdk:"provisioned_azure_tenant"`
	ProvisionedInternalLDAP                 types.Object `tfsdk:"provisioned_internal_ldap"`
	ProvisionedLDAP                         types.Object `tfsdk:"provisioned_ldap"`
	ProvisionedLDAPDirectory                types.Object `tfsdk:"provisioned_ldap_directory"`
	ProvisionedNamespace                    types.Object `tfsdk:"provisioned_namespace"`
	ProvisionedSCIM                         types.Object `tfsdk:"provisioned_scim"`
}

var provisioningProvisionedSystemLinkableWrapperAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedSystemLinkableWrapper(false)
var provisioningProvisionedSystemLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedSystemLinkableWrapper(true)

type provisioningProvisionedSystemLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var provisioningProvisionedSystemPrimerAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedSystemPrimer(false)
var provisioningProvisionedSystemPrimerAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedSystemPrimer(true)

type provisioningProvisionedSystemPrimerDataDS struct {
	Links                                   types.Set    `tfsdk:"links"`
	Permissions                             types.Set    `tfsdk:"permissions"`
	Active                                  types.Bool   `tfsdk:"active"`
	Name                                    types.String `tfsdk:"name"`
	OrganizationalUnit                      types.Object `tfsdk:"organizational_unit"`
	ProvisioningProvisionedSystemPrimerType types.String `tfsdk:"type"`
	UUID                                    types.String `tfsdk:"uuid"`
}

var provisioningProvisionedSystemPrimerLinkableWrapperAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedSystemPrimerLinkableWrapper(false)
var provisioningProvisionedSystemPrimerLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedSystemPrimerLinkableWrapper(true)

type provisioningProvisionedSystemPrimerLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var provisioningProvisionedSystem_additionalObjectsAttrTypesDS = objectAttrsTypeDSProvisioningProvisionedSystem_additionalObjects(false)
var provisioningProvisionedSystem_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisionedSystem_additionalObjects(true)

type provisioningProvisionedSystem_additionalObjectsDataDS struct {
	Account               types.Object `tfsdk:"account"`
	Audit                 types.Object `tfsdk:"audit"`
	IssuedPermissions     types.List   `tfsdk:"issued_permissions"`
	LoginName             types.String `tfsdk:"login_name"`
	ManagementPermissions types.Object `tfsdk:"management_permissions"`
	Markers               types.Object `tfsdk:"markers"`
	Statistics            types.Object `tfsdk:"statistics"`
	SupportedGroupTypes   types.Object `tfsdk:"supported_group_types"`
}

var provisioningProvisioningManagementPermissionsAttrTypesDS = objectAttrsTypeDSProvisioningProvisioningManagementPermissions(false)
var provisioningProvisioningManagementPermissionsAttrTypesDSRecurse = objectAttrsTypeDSProvisioningProvisioningManagementPermissions(true)

type provisioningProvisioningManagementPermissionsDataDS struct {
	CreateNewGroupsAllowed       types.Bool `tfsdk:"create_new_groups_allowed"`
	CreateServiceAccountsAllowed types.Bool `tfsdk:"create_service_accounts_allowed"`
	ReuseExistingGroupsAllowed   types.Bool `tfsdk:"reuse_existing_groups_allowed"`
}

var serviceaccountServiceAccountAttrTypesDS = objectAttrsTypeDSServiceaccountServiceAccount(false)
var serviceaccountServiceAccountAttrTypesDSRecurse = objectAttrsTypeDSServiceaccountServiceAccount(true)

type serviceaccountServiceAccountDataDS struct {
	Links                  types.Set    `tfsdk:"links"`
	Permissions            types.Set    `tfsdk:"permissions"`
	Active                 types.Bool   `tfsdk:"active"`
	Name                   types.String `tfsdk:"name"`
	System                 types.Object `tfsdk:"system"`
	Username               types.String `tfsdk:"username"`
	UUID                   types.String `tfsdk:"uuid"`
	Additional             types.List   `tfsdk:"additional"`
	Audit                  types.Object `tfsdk:"audit" tkhao:"audit"`
	Groups                 types.List   `tfsdk:"groups" tkhao:"groups"`
	Secret                 types.Object `tfsdk:"secret" tkhao:"secret"`
	Description            types.String `tfsdk:"description"`
	Password               types.Object `tfsdk:"password"`
	PasswordRotation       types.String `tfsdk:"password_rotation"`
	TechnicalAdministrator types.Object `tfsdk:"technical_administrator"`
}

var serviceaccountServiceAccountGroupAttrTypesDS = objectAttrsTypeDSServiceaccountServiceAccountGroup(false)
var serviceaccountServiceAccountGroupAttrTypesDSRecurse = objectAttrsTypeDSServiceaccountServiceAccountGroup(true)

type serviceaccountServiceAccountGroupDataDS struct {
	Links                               types.Set    `tfsdk:"links"`
	Permissions                         types.Set    `tfsdk:"permissions"`
	DisplayName                         types.String `tfsdk:"display_name"`
	NameInSystem                        types.String `tfsdk:"name_in_system"`
	ProvisioningGroupOnSystemPrimerType types.String `tfsdk:"type"`
	ShortNameInSystem                   types.String `tfsdk:"short_name_in_system"`
	Additional                          types.List   `tfsdk:"additional"`
	Audit                               types.Object `tfsdk:"audit" tkhao:"audit"`
}

var serviceaccountServiceAccountGroupLinkableWrapperAttrTypesDS = objectAttrsTypeDSServiceaccountServiceAccountGroupLinkableWrapper(false)
var serviceaccountServiceAccountGroupLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSServiceaccountServiceAccountGroupLinkableWrapper(true)

type serviceaccountServiceAccountGroupLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var serviceaccountServiceAccountGroup_additionalObjectsAttrTypesDS = objectAttrsTypeDSServiceaccountServiceAccountGroup_additionalObjects(false)
var serviceaccountServiceAccountGroup_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSServiceaccountServiceAccountGroup_additionalObjects(true)

type serviceaccountServiceAccountGroup_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
}

var serviceaccountServiceAccountLinkableWrapperAttrTypesDS = objectAttrsTypeDSServiceaccountServiceAccountLinkableWrapper(false)
var serviceaccountServiceAccountLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSServiceaccountServiceAccountLinkableWrapper(true)

type serviceaccountServiceAccountLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var serviceaccountServiceAccountPrimerAttrTypesDS = objectAttrsTypeDSServiceaccountServiceAccountPrimer(false)
var serviceaccountServiceAccountPrimerAttrTypesDSRecurse = objectAttrsTypeDSServiceaccountServiceAccountPrimer(true)

type serviceaccountServiceAccountPrimerDataDS struct {
	Links       types.Set    `tfsdk:"links"`
	Permissions types.Set    `tfsdk:"permissions"`
	Active      types.Bool   `tfsdk:"active"`
	Name        types.String `tfsdk:"name"`
	System      types.Object `tfsdk:"system"`
	Username    types.String `tfsdk:"username"`
	UUID        types.String `tfsdk:"uuid"`
}

var serviceaccountServiceAccountPrimerLinkableWrapperAttrTypesDS = objectAttrsTypeDSServiceaccountServiceAccountPrimerLinkableWrapper(false)
var serviceaccountServiceAccountPrimerLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSServiceaccountServiceAccountPrimerLinkableWrapper(true)

type serviceaccountServiceAccountPrimerLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var serviceaccountServiceAccount_additionalObjectsAttrTypesDS = objectAttrsTypeDSServiceaccountServiceAccount_additionalObjects(false)
var serviceaccountServiceAccount_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSServiceaccountServiceAccount_additionalObjects(true)

type serviceaccountServiceAccount_additionalObjectsDataDS struct {
	Audit  types.Object `tfsdk:"audit"`
	Groups types.List   `tfsdk:"groups"`
	Secret types.Object `tfsdk:"secret"`
}

var vaultPasswordMetadataAttrTypesDS = objectAttrsTypeDSVaultPasswordMetadata(false)
var vaultPasswordMetadataAttrTypesDSRecurse = objectAttrsTypeDSVaultPasswordMetadata(true)

type vaultPasswordMetadataDataDS struct {
	Dictionary   types.Bool   `tfsdk:"dictionary"`
	Duplicate    types.Bool   `tfsdk:"duplicate"`
	Hash         types.String `tfsdk:"hash"`
	Length       types.Int64  `tfsdk:"length"`
	LowerCount   types.Int64  `tfsdk:"lower_count"`
	NumberCount  types.Int64  `tfsdk:"number_count"`
	SpecialCount types.Int64  `tfsdk:"special_count"`
	Strength     types.Int64  `tfsdk:"strength"`
	UpperCount   types.Int64  `tfsdk:"upper_count"`
}

var vaultVaultAttrTypesDS = objectAttrsTypeDSVaultVault(false)
var vaultVaultAttrTypesDSRecurse = objectAttrsTypeDSVaultVault(true)

type vaultVaultDataDS struct {
	Links           types.Set    `tfsdk:"links"`
	Permissions     types.Set    `tfsdk:"permissions"`
	AccessAvailable types.Bool   `tfsdk:"access_available"`
	Name            types.String `tfsdk:"name"`
	Records         types.Set    `tfsdk:"records"`
}

var vaultVaultHolderAttrTypesDS = objectAttrsTypeDSVaultVaultHolder(false)
var vaultVaultHolderAttrTypesDSRecurse = objectAttrsTypeDSVaultVaultHolder(true)

type vaultVaultHolderDataDS struct {
}

var vaultVaultRecordAttrTypesDS = objectAttrsTypeDSVaultVaultRecord(false)
var vaultVaultRecordAttrTypesDSRecurse = objectAttrsTypeDSVaultVaultRecord(true)

type vaultVaultRecordDataDS struct {
	Links            types.Set    `tfsdk:"links"`
	Permissions      types.Set    `tfsdk:"permissions"`
	Color            types.String `tfsdk:"color"`
	Name             types.String `tfsdk:"name"`
	ShareEndTime     types.String `tfsdk:"share_end_time"`
	UUID             types.String `tfsdk:"uuid"`
	Additional       types.List   `tfsdk:"additional"`
	Audit            types.Object `tfsdk:"audit" tkhao:"audit"`
	Parent           types.Object `tfsdk:"parent" tkhao:"parent"`
	PasswordMetadata types.Object `tfsdk:"password_metadata" tkhao:"passwordMetadata"`
	Secret           types.Object `tfsdk:"secret" tkhao:"secret"`
	ShareSummary     types.Object `tfsdk:"share_summary" tkhao:"shareSummary"`
	Shares           types.List   `tfsdk:"shares" tkhao:"shares"`
	Tile             types.Object `tfsdk:"tile" tkhao:"tile"`
	Vaultholder      types.Object `tfsdk:"vaultholder" tkhao:"vaultholder"`
	Derived          types.Bool   `tfsdk:"derived"`
	EndDate          types.String `tfsdk:"end_date"`
	Filename         types.String `tfsdk:"filename"`
	Types            types.Set    `tfsdk:"types"`
	URL              types.String `tfsdk:"url"`
	Username         types.String `tfsdk:"username"`
	WarningPeriod    types.String `tfsdk:"warning_period"`
}

var vaultVaultRecordPrimerAttrTypesDS = objectAttrsTypeDSVaultVaultRecordPrimer(false)
var vaultVaultRecordPrimerAttrTypesDSRecurse = objectAttrsTypeDSVaultVaultRecordPrimer(true)

type vaultVaultRecordPrimerDataDS struct {
	Links        types.Set    `tfsdk:"links"`
	Permissions  types.Set    `tfsdk:"permissions"`
	Color        types.String `tfsdk:"color"`
	Name         types.String `tfsdk:"name"`
	ShareEndTime types.String `tfsdk:"share_end_time"`
	UUID         types.String `tfsdk:"uuid"`
}

var vaultVaultRecordPrimerLinkableWrapperAttrTypesDS = objectAttrsTypeDSVaultVaultRecordPrimerLinkableWrapper(false)
var vaultVaultRecordPrimerLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSVaultVaultRecordPrimerLinkableWrapper(true)

type vaultVaultRecordPrimerLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var vaultVaultRecordSecretsAttrTypesDS = objectAttrsTypeDSVaultVaultRecordSecrets(false)
var vaultVaultRecordSecretsAttrTypesDSRecurse = objectAttrsTypeDSVaultVaultRecordSecrets(true)

type vaultVaultRecordSecretsDataDS struct {
	Comment  types.String `tfsdk:"comment"`
	File     types.String `tfsdk:"file"`
	Password types.String `tfsdk:"password"`
	Totp     types.String `tfsdk:"totp"`
}

var vaultVaultRecordShareAttrTypesDS = objectAttrsTypeDSVaultVaultRecordShare(false)
var vaultVaultRecordShareAttrTypesDSRecurse = objectAttrsTypeDSVaultVaultRecordShare(true)

type vaultVaultRecordShareDataDS struct {
	Name                      types.String `tfsdk:"name"`
	VaultVaultRecordShareType types.String `tfsdk:"type"`
}

var vaultVaultRecordShareSummaryAttrTypesDS = objectAttrsTypeDSVaultVaultRecordShareSummary(false)
var vaultVaultRecordShareSummaryAttrTypesDSRecurse = objectAttrsTypeDSVaultVaultRecordShareSummary(true)

type vaultVaultRecordShareSummaryDataDS struct {
	Children types.Set    `tfsdk:"children"`
	Parent   types.Object `tfsdk:"parent"`
}

var vaultVaultRecord_additionalObjectsAttrTypesDS = objectAttrsTypeDSVaultVaultRecord_additionalObjects(false)
var vaultVaultRecord_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSVaultVaultRecord_additionalObjects(true)

type vaultVaultRecord_additionalObjectsDataDS struct {
	Audit            types.Object `tfsdk:"audit"`
	Parent           types.Object `tfsdk:"parent"`
	PasswordMetadata types.Object `tfsdk:"password_metadata"`
	Secret           types.Object `tfsdk:"secret"`
	ShareSummary     types.Object `tfsdk:"share_summary"`
	Shares           types.List   `tfsdk:"shares"`
	Tile             types.Object `tfsdk:"tile"`
	Vaultholder      types.Object `tfsdk:"vaultholder"`
}

var webhookWebhookAttrTypesDS = objectAttrsTypeDSWebhookWebhook(false)
var webhookWebhookAttrTypesDSRecurse = objectAttrsTypeDSWebhookWebhook(true)

type webhookWebhookDataDS struct {
	Links                types.Set    `tfsdk:"links"`
	Permissions          types.Set    `tfsdk:"permissions"`
	Additional           types.List   `tfsdk:"additional"`
	Account              types.Object `tfsdk:"account"`
	Active               types.Bool   `tfsdk:"active"`
	Audit                types.Object `tfsdk:"audit" tkhao:"audit"`
	AllTypes             types.Bool   `tfsdk:"all_types"`
	AuthenticationScheme types.String `tfsdk:"authentication_scheme"`
	BasicAuthPassword    types.String `tfsdk:"basic_auth_password"`
	BasicAuthUsername    types.String `tfsdk:"basic_auth_username"`
	BearerToken          types.String `tfsdk:"bearer_token"`
	Client               types.Object `tfsdk:"client"`
	ClientCertificate    types.Object `tfsdk:"client_certificate"`
	CustomHeaderName     types.String `tfsdk:"custom_header_name"`
	CustomHeaderValue    types.String `tfsdk:"custom_header_value"`
	Directory            types.Object `tfsdk:"directory"`
	Group                types.Object `tfsdk:"group"`
	Name                 types.String `tfsdk:"name"`
	System               types.Object `tfsdk:"system"`
	TLS                  types.String `tfsdk:"tls"`
	TrustedCertificate   types.Object `tfsdk:"trusted_certificate"`
	Types                types.Set    `tfsdk:"types"`
	URL                  types.String `tfsdk:"url"`
	UUID                 types.String `tfsdk:"uuid"`
	VerbosePayloads      types.Bool   `tfsdk:"verbose_payloads"`
}

var webhookWebhookLinkableWrapperAttrTypesDS = objectAttrsTypeDSWebhookWebhookLinkableWrapper(false)
var webhookWebhookLinkableWrapperAttrTypesDSRecurse = objectAttrsTypeDSWebhookWebhookLinkableWrapper(true)

type webhookWebhookLinkableWrapperDataDS struct {
	Items types.Set `tfsdk:"items"`
}

var webhookWebhook_additionalObjectsAttrTypesDS = objectAttrsTypeDSWebhookWebhook_additionalObjects(false)
var webhookWebhook_additionalObjectsAttrTypesDSRecurse = objectAttrsTypeDSWebhookWebhook_additionalObjects(true)

type webhookWebhook_additionalObjectsDataDS struct {
	Audit types.Object `tfsdk:"audit"`
}
