name: Build
on:
  push:
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
  
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
    
      - name: Build
        run: go build -v ./...
